In [1]:
import re
import time
import requests
import pandas as pd
from pathlib import Path
from bs4 import BeautifulSoup, XMLParsedAsHTMLWarning
import warnings
from google.colab import files

warnings.filterwarnings("ignore", category=XMLParsedAsHTMLWarning)

In [2]:
uploaded = files.upload()
print("Uploaded:", list(uploaded.keys()))

Uploaded: []

In [3]:
remaining = pd.read_csv("remaining_52_files_rebuilt.csv")
events_clean = pd.read_csv("events_clean.csv")

for df in [remaining, events_clean]:
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["filing_type"] = df["filing_type"].astype(str).str.strip().str.upper()
    df["accession_number"] = df["accession_number"].astype(str).str.strip()

remaining["filing_date"] = pd.to_datetime(remaining["filing_date"], errors="coerce").dt.strftime("%Y-%m-%d")
events_clean["filing_date"] = pd.to_datetime(events_clean["filing_date"], errors="coerce").dt.strftime("%Y-%m-%d")

repair_df = remaining.merge(
    events_clean[["ticker", "cik", "filing_date", "filing_type", "accession_number"]],
    on=["ticker", "filing_date", "filing_type", "accession_number"],
    how="left"
)

print("Rows after merge:", len(repair_df))
print("Missing cik:", repair_df["cik"].isna().sum())
display(repair_df.head())

Rows after merge: 52
Missing cik: 0

,ticker,filing_date,filing_type,accession_number,mda_filename,word_count_actual,digit_ratio_full,good_start_detected,suspicious_start_detected,contains_market_risk_start,...,needs_manual_review,review_reason,manual_label,notes,notes_final,strict_label,strict_notes,original_manual_label,original_notes,cik
0,AAPL,2019-10-31,10-K,0000320193-19-000119,AAPL_20191031_10-K_000032019319000119.txt,1018,0.015798,False,True,True,...,True,flagged,incorrect,NaN,NaN,incorrect,NaN,incorrect,NaN,320193
1,ABT,2023-02-17,10-K,0001628280-23-004026,ABT_20230217_10-K_000162828023004026.txt,723,0.060734,False,True,True,...,True,flagged,incorrect,NaN,NaN,incorrect,NaN,incorrect,NaN,1800
2,ABT,2024-02-16,10-K,0001628280-24-005348,ABT_20240216_10-K_000162828024005348.txt,733,0.059546,False,True,True,...,True,flagged,incorrect,NaN,NaN,incorrect,NaN,incorrect,NaN,1800
3,CMCSA,2022-02-02,10-K,0001166691-22-000009,CMCSA_20220202_10-K_000116669122000009.txt,1249,0.039080,False,True,True,...,True,flagged,incorrect,NaN,NaN,incorrect,NaN,incorrect,NaN,1166691
4,CMCSA,2023-02-03,10-K,0001166691-23-000010,CMCSA_20230203_10-K_000116669123000010.txt,1231,0.036038,False,True,True,...,True,flagged,incorrect,NaN,NaN,incorrect,NaN,incorrect,NaN,1166691

In [4]:
ticker_counts = repair_df["ticker"].value_counts().reset_index()
ticker_counts.columns = ["ticker", "count"]
display(ticker_counts)

   ticker  count
0     USB     14
1     JCI     13
2    SCHW      6
3    KLAC      5
4      PH      3
5   CMCSA      3
6    CRWD      3
7     ABT      2
8    AAPL      1
9     COF      1
10    PNC      1

In [5]:
BASE_DIR = Path("/content/family_rescue")
OUT_DIR = BASE_DIR / "repaired_txt"
BASE_DIR.mkdir(parents=True, exist_ok=True)
OUT_DIR.mkdir(parents=True, exist_ok=True)

REPAIR_LOG_CSV = BASE_DIR / "family_rescue_log.csv"
REVIEW_CSV = BASE_DIR / "family_rescue_review.csv"

In [6]:
HEADERS = {
    "User-Agent": "Cardiff University Student abhishekjc23@gmail.com",
    "Accept-Encoding": "gzip, deflate",
    "Host": "www.sec.gov"
}

def cik_nolead(cik):
    if pd.isna(cik):
        return None
    return str(int(float(cik)))

def acc_nodash(acc):
    return str(acc).replace("-", "")

def filing_base_url(cik, accession_number):
    return f"https://www.sec.gov/Archives/edgar/data/{cik_nolead(cik)}/{acc_nodash(accession_number)}"

def index_json_url(cik, accession_number):
    return filing_base_url(cik, accession_number) + "/index.json"

def get_index_json(cik, accession_number):
    url = index_json_url(cik, accession_number)
    r = requests.get(url, headers=HEADERS, timeout=30)
    r.raise_for_status()
    return r.json()

def safe_int(value, default=0):
    try:
        value = str(value).strip()
        if value == "" or value.lower() == "none":
            return default
        return int(value)
    except Exception:
        return default

def choose_primary_doc(index_json, filing_type):
    try:
        items = index_json["directory"]["item"]
    except Exception:
        return None

    docs = []
    for x in items:
        name = str(x.get("name", ""))
        lower = name.lower()
        if lower.endswith((".htm", ".html", ".txt")):
            docs.append(x)

    if not docs:
        return None

    bad_words = ["ex-", "exhibit", "xbrl", "xml", "graphic", "image", "zip", "def14a", "8-k"]
    filtered = []
    for d in docs:
        nm = str(d.get("name", "")).lower()
        if any(b in nm for b in bad_words):
            continue
        filtered.append(d)

    if not filtered:
        filtered = docs

    ft = filing_type.lower().replace("-", "").replace("_", "")
    filing_pref = []
    for d in filtered:
        nm = str(d.get("name", "")).lower().replace("-", "").replace("_", "")
        if ft in nm:
            filing_pref.append(d)
        elif filing_type == "10-K" and "10k" in nm:
            filing_pref.append(d)
        elif filing_type == "10-Q" and "10q" in nm:
            filing_pref.append(d)

    if filing_pref:
        filtered = filing_pref

    filtered = sorted(filtered, key=lambda x: safe_int(x.get("size", 0), 0), reverse=True)
    return filtered[0]["name"] if filtered else None

def download_filing_doc(cik, accession_number, filename):
    url = filing_base_url(cik, accession_number) + f"/{filename}"
    r = requests.get(url, headers=HEADERS, timeout=30)
    r.raise_for_status()
    return r.text

def html_to_text(html):
    soup = BeautifulSoup(html, "lxml")
    for tag in soup(["script", "style", "ix:header", "header", "footer"]):
        tag.decompose()
    text = soup.get_text("\n")
    text = text.replace("\xa0", " ")
    text = text.replace("’", "'")
    text = re.sub(r"\r", "\n", text)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{2,}", "\n\n", text)
    return text.strip()

In [7]:
def preview_unresolved_row(i, start_chars=2500, end_chars=1200):
    row = repair_df.iloc[i]
    idx = get_index_json(row["cik"], row["accession_number"])
    primary_doc = choose_primary_doc(idx, row["filing_type"])
    html = download_filing_doc(row["cik"], row["accession_number"], primary_doc)
    text = html_to_text(html)

    print("=" * 120)
    print("ROW:", i)
    print("TICKER:", row["ticker"])
    print("DATE:", row["filing_date"])
    print("TYPE:", row["filing_type"])
    print("PRIMARY DOC:", primary_doc)
    print("=" * 120)
    print("\n--- START OF FILING TEXT ---\n")
    print(text[:start_chars])
    print("\n--- END OF FILING TEXT ---\n")
    print(text[-end_chars:])
    print("\nWord count:", len(re.findall(r"\b[a-zA-Z]+\b", text)))
    print("=" * 120)

In [8]:
preview_unresolved_row(0)

========================================================================================================================
ROW: 0
TICKER: AAPL
DATE: 2019-10-31
TYPE: 10-K
PRIMARY DOC: a10-k20199282019.htm
========================================================================================================================

--- START OF FILING TEXT ---

Document


UNITED STATES
SECURITIES AND EXCHANGE COMMISSION
Washington, D.C. 20549

FORM
10-K


(Mark One)
☒

ANNUAL REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934
For the fiscal year ended
September 28, 2019
or
☐

TRANSITION REPORT PURSUANT TO SECTION 13 OR 15(d) OF THE SECURITIES EXCHANGE ACT OF 1934
For the transition period from

 to

.
Commission File Number:
001-36743

Apple Inc.
(Exact name of Registrant as specified in its charter)

California

94-2404110
(State or other jurisdiction
of incorporation or organization)

(I.R.S. Employer Identification No.)





One Apple Park Way


Cupertino

California

95014
(Address of principal executive offices)

(Zip Code)
(
408
)
996-1010
(Registrant's telephone number, including area code)

Securities registered pursuant to Section 12(b) of the Act:
Title of each class
Trading symbol(s)
Name of each exchange on which registered
Common Stock, $0.00001 par value per share
AAPL
The Nasdaq Stock Market LLC
1.000% Notes due 2022
—
The Nasdaq Stock Market LLC
1.375% Notes due 2024
—
The Nasdaq Stock Market LLC
0.875% Notes due 2025
—
The Nasdaq Stock Market LLC
1.625% Notes due 2026
—
The Nasdaq Stock Market LLC
2.000% Notes due 2027
—
The Nasdaq Stock Market LLC
1.375% Notes due 2029
—
The Nasdaq Stock Market LLC
3.050% Notes due 2029
—
The Nasdaq Stock Market LLC
3.600% Notes due 2042
—
The Nasdaq Stock Market LLC
Securities registered pursuant to Section 12(g) of the Act: None

Indicate by check mark if the Registrant is a well-known seasoned issuer, as defined in Rule 405 of the Securities Act.
Yes

☒
 No
☐
Indicate by check mark if the Registrant is not required to file reports pursuant to Section 13 or Section 15(d) of the Act.
Yes
☐

No

☒
Indicate by check mark whether the Registrant (1) has filed all reports required to be filed by Section 13 or 15(d) of the Securities Exchange Act of 1934 during the preceding 12 months (or for such shorter period that the Registrant was required to file such reports), and (2) has been subject to such filing requirements for the past 90 days.
Yes

☒
 No
☐
Indicate by check mark whether the Registrant has submitted electronically every Interactive Data File required to be submitted pursuant to Rule 405 of Regulation S-T (§232.405 of this chapter) during the preceding 12 months (or for such shorter period that the Registrant was required to submit such files).
Yes

☒
 No
☐
Indicate by check mark whether th

--- END OF FILING TEXT ---

utes, may do or cause to be done by virtue hereof.
Pursuant to the requirements of the Securities Exchange Act of 1934, this report has been signed below by the following persons on behalf of the Registrant and in the capacities and on the dates indicated:
Name

Title

Date





/s/ Timothy D. Cook

Chief Executive Officer and Director
(Principal Executive Officer)

October 30, 2019
TIMOTHY D. COOK








/s/ Luca Maestri

Senior Vice President, Chief Financial Officer
(Principal Financial Officer)

October 30, 2019
LUCA MAESTRI








/s/ Chris Kondo

Senior Director of Corporate Accounting
(Principal Accounting Officer)

October 30, 2019
CHRIS KONDO








/s/ James A. Bell

Director

October 30, 2019
JAMES A. BELL








/s/ Al Gore

Director

October 30, 2019
AL GORE








/s/ Andrea Jung

Director

October 30, 2019
ANDREA JUNG








/s/ Arthur D. Levinson

Director

October 30, 2019
ARTHUR D. LEVINSON








/s/ Ronald D. Sugar

Director

October 30, 2019
RONALD D. SUGAR








/s/ Susan L. Wagner

Director

October 30, 2019
SUSAN L. WAGNER



Apple Inc. | 2019 Form 10-K |
64

Word count: 32984
========================================================================================================================

In [9]:
def show_ticker_rows(ticker):
    sub = repair_df.loc[repair_df["ticker"] == ticker, ["ticker", "filing_date", "filing_type", "accession_number"]].copy()
    print("Rows for", ticker, "=", len(sub))
    display(sub.reset_index())

In [10]:
show_ticker_rows("AAPL")
show_ticker_rows("ABT")
show_ticker_rows("CMCSA")

Rows for AAPL = 1

   index ticker filing_date filing_type      accession_number
0      0   AAPL  2019-10-31        10-K  0000320193-19-000119

Rows for ABT = 2

   index ticker filing_date filing_type      accession_number
0      1    ABT  2023-02-17        10-K  0001628280-23-004026
1      2    ABT  2024-02-16        10-K  0001628280-24-005348

Rows for CMCSA = 3

   index ticker filing_date filing_type      accession_number
0      3  CMCSA  2022-02-02        10-K  0001166691-22-000009
1      4  CMCSA  2023-02-03        10-K  0001166691-23-000010
2      5  CMCSA  2024-01-31        10-K  0001166691-24-000011

In [11]:
FAMILY_RULES = {
    # Examples - edit as needed after previewing one filing per ticker
    "AAPL": {
        "10-K": {
            "start_patterns": [
                r"item\s*7[\.\-:\s]+management[' ]s discussion and analysis of financial condition and results of operations",
            ],
            "end_patterns": [
                r"item\s*7a[\.\-:\s]+quantitative and qualitative disclosures about market risk",
                r"item\s*8[\.\-:\s]+financial statements",
            ],
        }
    },
    "ABT": {
        "10-K": {
            "start_patterns": [
                r"item\s*7[\.\-:\s]+management[' ]s discussion and analysis of financial condition and results of operations",
            ],
            "end_patterns": [
                r"item\s*7a[\.\-:\s]+quantitative and qualitative disclosures about market risk",
                r"item\s*8[\.\-:\s]+financial statements",
            ],
        }
    },
    "CMCSA": {
        "10-K": {
            "start_patterns": [
                r"item\s*7[\.\-:\s]+management[' ]s discussion and analysis of financial condition and results of operations",
            ],
            "end_patterns": [
                r"item\s*7a[\.\-:\s]+quantitative and qualitative disclosures about market risk",
                r"item\s*8[\.\-:\s]+financial statements",
            ],
        }
    },
    "KLAC": {
        "10-K": {
            "start_patterns": [
                r"item\s*7[\.\-:\s]+management[' ]s discussion and analysis of financial condition and results of operations",
            ],
            "end_patterns": [
                r"item\s*7a[\.\-:\s]+quantitative and qualitative disclosures about market risk",
                r"item\s*8[\.\-:\s]+financial statements",
            ],
        }
    },
}

In [12]:
def extract_with_family_rule(text, ticker, filing_type):
    text = text.replace("\xa0", " ")
    text = text.replace("’", "'")
    low = text.lower()

    rules = FAMILY_RULES.get(ticker, {}).get(filing_type, None)
    if rules is None:
        return None, "NO_RULE"

    starts = []
    for pat in rules["start_patterns"]:
        for m in re.finditer(pat, low, flags=re.I):
            starts.append(m.start())

    ends = []
    for pat in rules["end_patterns"]:
        for m in re.finditer(pat, low, flags=re.I):
            ends.append(m.start())

    starts = sorted(set(starts))
    ends = sorted(set(ends))

    if not starts:
        return None, "NO_START"
    if not ends:
        return None, "NO_END"

    # Prefer later starts to avoid TOC/reference hits
    doc_len = len(text)
    starts = [s for s in starts if s > doc_len * 0.10] or starts

    best_pair = None
    best_span = None

    for s in starts:
        valid_ends = [e for e in ends if e > s]
        if not valid_ends:
            continue

        e = valid_ends[0]
        span = e - s

        if 3000 <= span <= 400000:
            best_pair = (s, e)
            best_span = span
            break

        if best_pair is None:
            best_pair = (s, e)
            best_span = span

    if best_pair is None:
        return None, "NO_VALID_SPAN"

    s, e = best_pair
    mda = text[s:e].strip()

    wc = len(re.findall(r"\b[a-zA-Z]+\b", mda))
    if wc < 800:
        return None, "TOO_SHORT"

    first_500 = re.sub(r"\s+", " ", mda[:500]).lower()
    if filing_type == "10-K":
        good = ("item 7" in first_500 and "management's discussion" in first_500)
    else:
        good = ("item 2" in first_500 and "management's discussion" in first_500)

    if not good:
        return None, "BAD_START"

    if (
        "table of contents" in first_500 or
        "under the heading" in first_500 or
        "refer to item" in first_500 or
        "see item" in first_500
    ):
        return None, "BAD_START"

    return mda, "OK"

In [13]:
def repair_one_family_rule(row, sleep_seconds=0.2):
    ticker = row["ticker"]
    cik = row["cik"]
    filing_date = row["filing_date"]
    filing_type = row["filing_type"]
    accession_number = row["accession_number"]

    out = {
        "ticker": ticker,
        "filing_date": filing_date,
        "filing_type": filing_type,
        "accession_number": accession_number,
        "repair_status": "",
        "primary_doc": "",
        "repaired_filename": ""
    }

    try:
        if pd.isna(cik):
            out["repair_status"] = "NO_CIK"
            return out

        idx = get_index_json(cik, accession_number)
        primary_doc = choose_primary_doc(idx, filing_type)
        if primary_doc is None:
            out["repair_status"] = "NO_PRIMARY_DOC"
            return out

        out["primary_doc"] = primary_doc

        html = download_filing_doc(cik, accession_number, primary_doc)
        text = html_to_text(html)

        mda_text, status = extract_with_family_rule(text, ticker, filing_type)

        if status != "OK":
            out["repair_status"] = status
            return out

        fname = f"{ticker}_{filing_date}_{filing_type}_{accession_number}_FAMILY52.txt"
        with open(OUT_DIR / fname, "w", encoding="utf-8") as f:
            f.write(mda_text)

        out["repair_status"] = "OK"
        out["repaired_filename"] = fname

        time.sleep(sleep_seconds)
        return out

    except Exception as e:
        out["repair_status"] = f"ERROR: {str(e)[:120]}"
        return out

In [14]:
TARGET_TICKERS = ["AAPL", "ABT", "CMCSA", "KLAC"]

target_df = repair_df.loc[repair_df["ticker"].isin(TARGET_TICKERS)].copy()
print("Target rows:", len(target_df))
display(target_df[["ticker", "filing_date", "filing_type", "accession_number"]].head(20))

Target rows: 11

   ticker filing_date filing_type      accession_number
0    AAPL  2019-10-31        10-K  0000320193-19-000119
1     ABT  2023-02-17        10-K  0001628280-23-004026
2     ABT  2024-02-16        10-K  0001628280-24-005348
3   CMCSA  2022-02-02        10-K  0001166691-22-000009
4   CMCSA  2023-02-03        10-K  0001166691-23-000010
5   CMCSA  2024-01-31        10-K  0001166691-24-000011
23   KLAC  2019-08-16        10-K  0000319201-19-000031
24   KLAC  2021-08-06        10-K  0000319201-21-000029
25   KLAC  2022-04-29        10-Q  0000319201-22-000012
26   KLAC  2022-08-05        10-K  0000319201-22-000023
27   KLAC  2023-08-04        10-K  0000319201-23-000031

In [15]:
results = []

for i, row in target_df.iterrows():
    result = repair_one_family_rule(row)
    results.append(result)

    if len(results) % 10 == 0:
        print(f"Processed {len(results)}/{len(target_df)}")

repair_log = pd.DataFrame(results)
repair_log.to_csv(REPAIR_LOG_CSV, index=False)

print("Family repair complete.")
display(repair_log["repair_status"].value_counts())
display(repair_log.head())

Processed 10/11
Family repair complete.

repair_status
OK           3
TOO_SHORT    3
NO_START     2
BAD_START    2
NO_RULE      1
Name: count, dtype: int64

,ticker,filing_date,filing_type,accession_number,repair_status,primary_doc,repaired_filename
0,AAPL,2019-10-31,10-K,0000320193-19-000119,OK,a10-k20199282019.htm,AAPL_2019-10-31_10-K_0000320193-19-000119_FAMI...
1,ABT,2023-02-17,10-K,0001628280-23-004026,NO_START,abt-20221231x10kexx21.htm,
2,ABT,2024-02-16,10-K,0001628280-24-005348,NO_START,abt-20231231x10kexx312.htm,
3,CMCSA,2022-02-02,10-K,0001166691-22-000009,BAD_START,cmcsa-20211231.htm,
4,CMCSA,2023-02-03,10-K,0001166691-23-000010,BAD_START,cmcsa-20221231.htm,

In [16]:
def read_text_safe(path):
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        return f.read()

review_rows = []

for _, row in repair_log.loc[repair_log["repair_status"] == "OK"].iterrows():
    path = OUT_DIR / row["repaired_filename"]
    text = read_text_safe(path)

    review_rows.append({
        "ticker": row["ticker"],
        "filing_date": row["filing_date"],
        "filing_type": row["filing_type"],
        "accession_number": row["accession_number"],
        "repaired_filename": row["repaired_filename"],
        "word_count": len(re.findall(r"\b[a-zA-Z]+\b", text)),
        "first_300_chars": text[:300].replace("\n", " "),
        "first_1000_chars": text[:1000].replace("\n", " "),
    })

review_df = pd.DataFrame(review_rows)
review_df.to_csv(REVIEW_CSV, index=False)

print("Saved review CSV:", REVIEW_CSV)
display(review_df)

Saved review CSV: /content/family_rescue/family_rescue_review.csv

,ticker,filing_date,filing_type,accession_number,repaired_filename,word_count,first_300_chars,first_1000_chars
0,AAPL,2019-10-31,10-K,0000320193-19-000119,AAPL_2019-10-31_10-K_0000320193-19-000119_FAMI...,4715,Item 7. Management's Discussion and Analysis o...,Item 7. Management's Discussion and Analysis o...
1,CMCSA,2024-01-31,10-K,0001166691-24-000011,CMCSA_2024-01-31_10-K_0001166691-24-000011_FAM...,13100,Item 7: Management's Discussion and Analysis o...,Item 7: Management's Discussion and Analysis o...
2,KLAC,2023-08-04,10-K,0000319201-23-000031,KLAC_2023-08-04_10-K_0000319201-23-000031_FAMI...,10621,ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS O...,ITEM 7. MANAGEMENT'S DISCUSSION AND ANALYSIS O...

In [17]:
ok_family = repair_log.loc[
    repair_log["repair_status"] == "OK",
    ["ticker", "filing_date", "filing_type", "accession_number", "repaired_filename"]
].copy()

print("Family OK files:", len(ok_family))
display(ok_family)

Family OK files: 3

,ticker,filing_date,filing_type,accession_number,repaired_filename
0,AAPL,2019-10-31,10-K,0000320193-19-000119,AAPL_2019-10-31_10-K_0000320193-19-000119_FAMI...
5,CMCSA,2024-01-31,10-K,0001166691-24-000011,CMCSA_2024-01-31_10-K_0001166691-24-000011_FAM...
10,KLAC,2023-08-04,10-K,0000319201-23-000031,KLAC_2023-08-04_10-K_0000319201-23-000031_FAMI...

In [18]:
def preview_repaired_file(filename, start_chars=2500, end_chars=1200):
    path = OUT_DIR / filename
    if not path.exists():
        print("File not found:", path)
        return

    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        text = f.read()

    print("=" * 120)
    print("FILE:", filename)
    print("=" * 120)
    print("\n--- START PREVIEW ---\n")
    print(text[:start_chars])
    print("\n--- END PREVIEW ---\n")
    print(text[-end_chars:])
    print("\nWord count:", len(re.findall(r"\b[a-zA-Z]+\b", text)))
    print("=" * 120)

In [19]:
for i in range(len(ok_family)):
    fname = ok_family.iloc[i]["repaired_filename"]
    print(f"\n### Reviewing row {i}")
    preview_repaired_file(fname)

### Reviewing row 0
========================================================================================================================
FILE: AAPL_2019-10-31_10-K_0000320193-19-000119_FAMILY52.txt
========================================================================================================================

--- START PREVIEW ---

Item 7.
Management's Discussion and Analysis of Financial Condition and Results of Operations
This section and other parts of this Annual Report on Form 10-K (“Form 10-K”) contain forward-looking statements, within the meaning of the Private Securities Litigation Reform Act of 1995, that involve risks and uncertainties. Forward-looking statements provide current expectations of future events based on certain assumptions and include any statement that does not directly relate to any historical or current fact. Forward-looking statements can also be identified by words such as “future,” “anticipates,” “believes,” “estimates,” “expects,” “intends,” “plans,” “predicts,” “will,” “would,” “could,” “can,” “may,” and similar terms. Forward-looking statements are not guarantees of future performance and the Company's actual results may differ significantly from the results discussed in the forward-looking statements. Factors that might cause such differences include, but are not limited to, those discussed in Part I, Item 1A of this Form 10-K under the heading “Risk Factors,” which are incorporated herein by reference. The following discussion should be read in conjunction with the consolidated financial statements and accompanying notes included in Part II, Item 8 of this Form 10-K. Unless otherwise stated, all information presented herein is based on the Company's fiscal calendar, and references to particular years, quarters, months or periods refer to the Company's fiscal years ended in September and the associated quarters, months and periods of those fiscal years. Each of the terms the “Company” and “Apple” as used herein refers collectively to Apple Inc. and its wholly owned subsidiaries, unless otherwise stated. The Company assumes no obligation to revise or update any forward-looking statements for any reason, except as required by law.
This section of this Form 10-K generally discusses
2019
 and
2018
 items and year-to-year comparisons between
2019
 and
2018
. Discussions of
2017
 items and year-to-year comparisons between
2018
 and
2017
 that are not included in this Form 10-K can be found in “Management's Discussion and Analysis of Financial Condition and Results of Operations” in Part II, Item 7 of the Company's Annual Report on Form 10-K for the fiscal year ended
September 29, 2018
.
Fiscal Period
The Company's fiscal year is the 52- or 53-week period that ends on the last Saturday of September. The Company's fiscal years 2019 and 2018 spanned

--- END PREVIEW ---

0-K under the heading “Legal Proceedings” and in Part II, Item 8 of this Form 10-K in the Notes to Consolidated Financial Statements in Note 10, “Commitments and Contingencies,” the Company is subject to various legal proceedings and claims that arise in the ordinary course of business. The Company records a liability when it is probable that a loss has been incurred and the amount is reasonably estimable, the determination of which requires significant judgment. Except as described in Part II, Item 8 of this Form 10-K in the Notes to Consolidated Financial Statements in Note 10, “Commitments and Contingencies” under the heading “Contingencies,” in the opinion of management, there was not at least a reasonable possibility the Company may have incurred a material loss, or a material loss greater than a recorded accrual, concerning loss contingencies for asserted legal and other claims.
The outcome of litigation is inherently uncertain. If one or more legal matters were resolved against the Company in a reporting period for amounts above management's expectations, the Company's financial condition and operating results for that reporting period could be materially adversely affected.

Word count: 4715
========================================================================================================================

### Reviewing row 1
========================================================================================================================
FILE: CMCSA_2024-01-31_10-K_0001166691-24-000011_FAMILY52.txt
========================================================================================================================

--- START PREVIEW ---

Item 7: Management's Discussion and Analysis of Financial Condition and Results of Operations for additional information.
Share Repurchases
The table below summarizes Comcast's common stock repurchases during 2023.
Period
Total Number of
Shares
Purchased
Average
Price Per
Share
Total Number of
Shares
Purchased as
Part of Publicly
Announced
Authorization
Total Dollar
Amount
Purchased Under the Publicly Announced
Authorization
Maximum Dollar Value
of Shares That
May Yet Be Purchased
Under the Publicly
Announced
Authorization
(a)
First Quarter 2023
52,545,035
$
38.06
52,545,035
$
1,999,999,325
$
14,000,000,855
Second Quarter 2023
50,509,440
$
39.60
50,509,440
$
1,999,999,962
$
12,000,000,893
Third Quarter 2023
77,464,030
$
45.18
77,464,030
$
3,500,000,652
$
8,500,000,241
October 1-31, 2023
44,347,247
$
42.84
44,347,247
$
1,899,957,474
$
6,600,042,767
November 1-30, 2023
22,423,430
$
42.14
22,423,430
$
944,948,397
$
5,655,094,370
December 1-31, 2023
15,161,912
$
43.21
15,161,912
$
655,093,867
$
5,000,000,503
Total
262,451,094

$
41.91

262,451,094

$
10,999,999,677

$
5,000,000,503

(a)
In September 2022, our Board of Directors ap
proved a share repurchase program authorization of $20 billion. In January 2024, our Board of Directors approved a new share repurchase program authorization of $15 billion, which has no expiration date. We expect to repurchase additional shares of our Class A common stock under this authorization in the open market or in private transactions, subject to market and other conditions.
Comcast 2023 Annual Report on Form 10-K
30
Table of Contents
Stock Performance Graph
The following graph compares the annual percentage change in the cumulative total shareholder return on Comcast's Class A common stock during the five years ended December 31, 2023 with the cumulative total returns on the Standard & Poor's 500 Stock Index and a select peer group consisting of us and other companies engaged in the transmission and distribution and media industries. This peer group consists of our Class A common stock and the common stock of AT&T Inc., Charter Communications, Inc., Fox Corp. (Class A), Lumen Technologies, Inc., Paramount Global (Class B), T-Mobile US, Inc., Verizon Communications Inc., Warner Bros. Discovery Inc. and The Walt Disney Company (the “New Peer Group”).
Following the change in our segment reporting in 2023, we have updated the peer group presented to simplify the calculation, to remove DISH N

--- END PREVIEW ---

 contract term based on estimated relative value. Estimated relative value is generally based on terms of the contract and the nature of and potential revenue generation of the deliverables within the contract.
Capitalized film and television costs are subject to impairment testing when certain triggering events are identified. The substantial majority of our owned content is evaluated for impairment on an individual title basis. Licensed content that is not part of a fil
m group is tested for impairment primarily on a channel, network or platform basis, with the exception of our broadcast networks and owned local broadcast television stations, which are tested on a daypart basis. Sports rights are accounted for as executory contracts and are not subject to impairment. When performing an impairment assessment, we estimate fair value primarily based on a discounted cash flow analysis that involves significant judgment, including market participant estimates of future cash flows, which are supported by internal forecasts. Impairments of capitalized film and television costs were not material in any of the periods presented.
Comcast 2023 Annual Report on Form 10-K
56
Table of Contents

Word count: 13100
========================================================================================================================

### Reviewing row 2
========================================================================================================================
FILE: KLAC_2023-08-04_10-K_0000319201-23-000031_FAMILY52.txt
========================================================================================================================

--- START PREVIEW ---

ITEM 7.
MANAGEMENT'S DISCUSSION AND ANALYSIS OF FINANCIAL CONDITION AND RESULTS OF OPERATIONS
The following discussion of our financial condition and results of operations should be read in conjunction with our Consolidated Financial Statements and the related notes included in Item 8 “Financial Statements and Supplementary Data” in this Annual Report on Form 10-K. This discussion contains forward-looking statements, which involve risks and uncertainties. Our actual results could differ materially from those anticipated in the forward-looking statements as a result of certain factors,
35
Table of Contents
including but not limited to those discussed in Item 1A “Risk Factors” and elsewhere in this Annual Report on Form 10-K (see “Special Note Regarding Forward-Looking Statements”). Discussions and analysis of fiscal year 2022 as compared against fiscal year 2021 have been omitted and can be found in Item 7 of our Annual Report on Form 10-K for the fiscal year ended June 30, 2022, filed with the SEC.
EXECUTIVE SUMMARY
We are a leading supplier of process control and yield management solutions and services for the semiconductor and related electronics industries. Our broad portfolio of inspection and metrology products, and related service, software and other offerings, support R&D and manufacturing of ICs, wafers and reticles. Our products, services and expertise are used by our customers to measure, detect, analyze and resolve critical and nanometric level product defects, helping them to manage manufacturing process challenges and to obtain higher finish product yields at lower cost. We also offer advanced technology solutions to address various manufacturing needs of PCBs, FPDs, specialty semiconductor devices and other electronic components, including advanced packaging, LED, power devices, compound semiconductor, and data storage industries, as well as general materials research.
Our semiconductor customers generally operate in one or both of the major semiconductor device manufacturing markets: memory and foundry/logic. The pervasive and increasing needs for semiconductors in many consumer and industrial products, the rapid proliferation of new applications for more advanced semiconductor devices, and the increasing complexity associated with leading edge semiconductor manufacturing drives demand for our process control and yield management solutions. Continuing advancement of technology spurred by the economic, power and performance benefits of being

--- END PREVIEW ---

gional economies and the semiconductor, semiconductor-related and electronic device industries. Although cash requirements will fluctuate based on the timing and extent of these factors, we believe that cash generated from operations, together with the liquidity provided by existing cash and cash equivalents balances and our $1.50 billion Revolving Credit Facility, will be sufficient to satisfy our liquidity requirements associated with working capital needs, capital expenditures, cash dividends, stock repurchases and other contractual obligations, including repayment of outstanding debt, for at least the next 12 months.
Our credit ratings as of June 30, 2023 are summarized below:
Rating Agency
Rating
Fitch
A-
Moody's
A2
S&P
A-
In June 2022, S&P upgraded our senior unsecured credit rating from BBB+ to A-. In March 2022, Fitch upgraded our senior unsecured credit rating from BBB+ to A-. Factors that can affect our credit ratings include changes in our operating performance, the economic environment, conditions in the semiconductor and semiconductor capital equipment industries, our financial position, material acquisitions and changes in our business strategy.
52
Table of Contents

Word count: 10621
========================================================================================================================

In [20]:
ok_family = pd.read_csv("remaining52_ok_4_files_rich_review.csv") if False else ok_family.copy()

correct_keys_2 = {
    ("AAPL", "2019-10-31", "10-K"),
    ("KLAC", "2023-08-04", "10-K"),
}

ok_family["ticker"] = ok_family["ticker"].astype(str).str.strip().str.upper()
ok_family["filing_type"] = ok_family["filing_type"].astype(str).str.strip().str.upper()
ok_family["accession_number"] = ok_family["accession_number"].astype(str).str.strip()
ok_family["filing_date"] = pd.to_datetime(ok_family["filing_date"], errors="coerce").dt.strftime("%Y-%m-%d")

ok_family["manual_label"] = ""
ok_family["notes"] = ""

ok_family.loc[
    ok_family.apply(lambda r: (r["ticker"], r["filing_date"], r["filing_type"]) in correct_keys_2, axis=1),
    ["manual_label", "notes"]
] = ["correct", "accepted after manual preview"]

correct_2 = ok_family.loc[ok_family["manual_label"] == "correct"].copy()
correct_2.to_csv("/content/correct_2_files.csv", index=False)

print("Correct rows:", len(correct_2))
display(correct_2)

Correct rows: 2

,ticker,filing_date,filing_type,accession_number,repaired_filename,manual_label,notes
0,AAPL,2019-10-31,10-K,0000320193-19-000119,AAPL_2019-10-31_10-K_0000320193-19-000119_FAMI...,correct,accepted after manual preview
10,KLAC,2023-08-04,10-K,0000319201-23-000031,KLAC_2023-08-04_10-K_0000319201-23-000031_FAMI...,correct,accepted after manual preview

In [21]:
remaining_52 = pd.read_csv("remaining_52_files_rebuilt.csv")
correct_2 = pd.read_csv("/content/correct_2_files.csv")

for df in [remaining_52, correct_2]:
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["filing_type"] = df["filing_type"].astype(str).str.strip().str.upper()
    df["accession_number"] = df["accession_number"].astype(str).str.strip()
    df["filing_date"] = pd.to_datetime(df["filing_date"], errors="coerce").dt.strftime("%Y-%m-%d")

correct_2_keys = set(
    zip(
        correct_2["ticker"],
        correct_2["filing_date"],
        correct_2["filing_type"],
        correct_2["accession_number"]
    )
)

remaining_42 = remaining_52.loc[
    ~remaining_52.apply(
        lambda r: (r["ticker"], r["filing_date"], r["filing_type"], r["accession_number"]) in correct_2_keys,
        axis=1
    )
].copy()

remaining_42.to_csv("/content/remaining_42_files.csv", index=False)

print("Remaining unresolved files:", len(remaining_42))
display(remaining_42.head())

Remaining unresolved files: 50

,ticker,filing_date,filing_type,accession_number,mda_filename,word_count_actual,digit_ratio_full,good_start_detected,suspicious_start_detected,contains_market_risk_start,...,first_400_chars,needs_manual_review,review_reason,manual_label,notes,notes_final,strict_label,strict_notes,original_manual_label,original_notes
1,ABT,2023-02-17,10-K,0001628280-23-004026,ABT_20230217_10-K_000162828023004026.txt,723,0.060734,False,True,True,...,A. QUANTITATIVE AND QUALITATIVE DISCLOSURES AB...,True,flagged,incorrect,NaN,NaN,incorrect,NaN,incorrect,NaN
2,ABT,2024-02-16,10-K,0001628280-24-005348,ABT_20240216_10-K_000162828024005348.txt,733,0.059546,False,True,True,...,A. QUANTITATIVE AND QUALITATIVE DISCLOSURES AB...,True,flagged,incorrect,NaN,NaN,incorrect,NaN,incorrect,NaN
3,CMCSA,2022-02-02,10-K,0001166691-22-000009,CMCSA_20220202_10-K_000116669122000009.txt,1249,0.039080,False,True,True,...,A: Quantitative and Qualitative Disclosures Ab...,True,flagged,incorrect,NaN,NaN,incorrect,NaN,incorrect,NaN
4,CMCSA,2023-02-03,10-K,0001166691-23-000010,CMCSA_20230203_10-K_000116669123000010.txt,1231,0.036038,False,True,True,...,A: Quantitative and Qualitative Disclosures Ab...,True,flagged,incorrect,NaN,NaN,incorrect,NaN,incorrect,NaN
5,CMCSA,2024-01-31,10-K,0001166691-24-000011,CMCSA_20240131_10-K_000116669124000011.txt,1139,0.033118,False,True,True,...,A: Quantitative and Qualitative Disclosures Ab...,True,flagged,incorrect,NaN,NaN,incorrect,NaN,incorrect,NaN

In [22]:
target_df = repair_df.copy()

print("Rows to process:", len(target_df))
display(target_df[["ticker", "filing_date", "filing_type", "accession_number"]].head(20))

Rows to process: 52

   ticker filing_date filing_type      accession_number
0    AAPL  2019-10-31        10-K  0000320193-19-000119
1     ABT  2023-02-17        10-K  0001628280-23-004026
2     ABT  2024-02-16        10-K  0001628280-24-005348
3   CMCSA  2022-02-02        10-K  0001166691-22-000009
4   CMCSA  2023-02-03        10-K  0001166691-23-000010
5   CMCSA  2024-01-31        10-K  0001166691-24-000011
6     COF  2022-02-25        10-K  0000927628-22-000106
7    CRWD  2022-03-16        10-K  0001535527-22-000006
8    CRWD  2023-03-09        10-K  0001535527-23-000008
9    CRWD  2024-03-07        10-K  0001535527-24-000007
10    JCI  2020-07-31        10-Q  0000833444-20-000036
11    JCI  2021-01-29        10-Q  0000833444-21-000011
12    JCI  2021-04-30        10-Q  0000833444-21-000020
13    JCI  2021-07-30        10-Q  0000833444-21-000040
14    JCI  2022-02-02        10-Q  0000833444-22-000005
15    JCI  2022-05-04        10-Q  0000833444-22-000017
16    JCI  2022-08-04        10-Q  0000833444-22-000036
17    JCI  2023-02-01        10-Q  0000833444-23-000005
18    JCI  2023-05-05        10-Q  0000833444-23-000014
19    JCI  2023-08-02        10-Q  0000833444-23-000030

In [23]:
ticker_counts = repair_df["ticker"].value_counts().reset_index()
ticker_counts.columns = ["ticker", "count"]
display(ticker_counts)

   ticker  count
0     USB     14
1     JCI     13
2    SCHW      6
3    KLAC      5
4      PH      3
5   CMCSA      3
6    CRWD      3
7     ABT      2
8    AAPL      1
9     COF      1
10    PNC      1

In [24]:
show_ticker_rows("USB")
show_ticker_rows("JCI")
show_ticker_rows("SCHW")
show_ticker_rows("KLAC")

Rows for USB = 14

    index ticker filing_date filing_type      accession_number
0      38    USB  2020-05-07        10-Q  0001193125-20-136359
1      39    USB  2020-08-06        10-Q  0001193125-20-211979
2      40    USB  2020-11-05        10-Q  0001193125-20-286983
3      41    USB  2021-05-04        10-Q  0001193125-21-150169
4      42    USB  2021-08-03        10-Q  0001193125-21-234982
5      43    USB  2021-11-02        10-Q  0001193125-21-317037
6      44    USB  2022-05-03        10-Q  0001193125-22-138788
7      45    USB  2022-08-04        10-Q  0001193125-22-212040
8      46    USB  2022-11-01        10-Q  0001193125-22-275036
9      47    USB  2023-05-08        10-Q  0001193125-23-137980
10     48    USB  2023-08-07        10-Q  0001193125-23-204050
11     49    USB  2023-11-01        10-Q  0001193125-23-268341
12     50    USB  2024-05-01        10-Q  0000036104-24-000037
13     51    USB  2024-08-06        10-Q  0000036104-24-000052

Rows for JCI = 13

    index ticker filing_date filing_type      accession_number
0      10    JCI  2020-07-31        10-Q  0000833444-20-000036
1      11    JCI  2021-01-29        10-Q  0000833444-21-000011
2      12    JCI  2021-04-30        10-Q  0000833444-21-000020
3      13    JCI  2021-07-30        10-Q  0000833444-21-000040
4      14    JCI  2022-02-02        10-Q  0000833444-22-000005
5      15    JCI  2022-05-04        10-Q  0000833444-22-000017
6      16    JCI  2022-08-04        10-Q  0000833444-22-000036
7      17    JCI  2023-02-01        10-Q  0000833444-23-000005
8      18    JCI  2023-05-05        10-Q  0000833444-23-000014
9      19    JCI  2023-08-02        10-Q  0000833444-23-000030
10     20    JCI  2024-01-30        10-Q  0000833444-24-000011
11     21    JCI  2024-05-01        10-Q  0000833444-24-000029
12     22    JCI  2024-07-31        10-Q  0000833444-24-000052

Rows for SCHW = 6

   index ticker filing_date filing_type      accession_number
0     32   SCHW  2021-05-07        10-Q  0000316709-21-000029
1     33   SCHW  2022-05-09        10-Q  0000316709-22-000018
2     34   SCHW  2022-11-08        10-Q  0000316709-22-000045
3     35   SCHW  2024-05-09        10-Q  0000316709-24-000044
4     36   SCHW  2024-08-08        10-Q  0000316709-24-000060
5     37   SCHW  2024-11-08        10-Q  0000316709-24-000069

Rows for KLAC = 5

   index ticker filing_date filing_type      accession_number
0     23   KLAC  2019-08-16        10-K  0000319201-19-000031
1     24   KLAC  2021-08-06        10-K  0000319201-21-000029
2     25   KLAC  2022-04-29        10-Q  0000319201-22-000012
3     26   KLAC  2022-08-05        10-K  0000319201-22-000023
4     27   KLAC  2023-08-04        10-K  0000319201-23-000031

In [25]:
FAMILY_RULES = {
    "USB": {
        "10-Q": {
            "start_patterns": [
                r"item\s*2[\.\-:\s]+management[' ]s discussion and analysis of financial condition and results of operations",
                r"management[' ]s discussion and analysis of financial condition and results of operations",
            ],
            "end_patterns": [
                r"item\s*3[\.\-:\s]+quantitative and qualitative disclosures about market risk",
                r"item\s*4[\.\-:\s]+controls and procedures",
                r"^item\s*3\b",
                r"^item\s*4\b",
            ],
        }
    },

    "JCI": {
        "10-Q": {
            "start_patterns": [
                r"item\s*2[\.\-:\s]+management[' ]s discussion and analysis of financial condition and results of operations",
                r"management[' ]s discussion and analysis of financial condition and results of operations",
            ],
            "end_patterns": [
                r"item\s*3[\.\-:\s]+quantitative and qualitative disclosures about market risk",
                r"item\s*4[\.\-:\s]+controls and procedures",
                r"^item\s*3\b",
                r"^item\s*4\b",
            ],
        }
    },

    "SCHW": {
        "10-Q": {
            "start_patterns": [
                r"item\s*2[\.\-:\s]+management[' ]s discussion and analysis of financial condition and results of operations",
                r"management[' ]s discussion and analysis of financial condition and results of operations",
            ],
            "end_patterns": [
                r"item\s*3[\.\-:\s]+quantitative and qualitative disclosures about market risk",
                r"item\s*4[\.\-:\s]+controls and procedures",
                r"^item\s*3\b",
                r"^item\s*4\b",
            ],
        }
    },

    "KLAC": {
        "10-K": {
            "start_patterns": [
                r"item\s*7[\.\-:\s]+management[' ]s discussion and analysis of financial condition and results of operations",
                r"management[' ]s discussion and analysis of financial condition and results of operations",
            ],
            "end_patterns": [
                r"item\s*7a[\.\-:\s]+quantitative and qualitative disclosures about market risk",
                r"item\s*8[\.\-:\s]+financial statements",
                r"^item\s*8\b",
            ],
        },
        "10-Q": {
            "start_patterns": [
                r"item\s*2[\.\-:\s]+management[' ]s discussion and analysis of financial condition and results of operations",
                r"management[' ]s discussion and analysis of financial condition and results of operations",
            ],
            "end_patterns": [
                r"item\s*3[\.\-:\s]+quantitative and qualitative disclosures about market risk",
                r"item\s*4[\.\-:\s]+controls and procedures",
                r"^item\s*3\b",
                r"^item\s*4\b",
            ],
        }
    }
}

In [26]:
TARGET_TICKERS = ["USB", "JCI", "SCHW", "KLAC"]

target_df = repair_df.loc[repair_df["ticker"].isin(TARGET_TICKERS)].copy()

print("Target rows:", len(target_df))
display(target_df[["ticker", "filing_date", "filing_type", "accession_number"]])

Target rows: 38

   ticker filing_date filing_type      accession_number
10    JCI  2020-07-31        10-Q  0000833444-20-000036
11    JCI  2021-01-29        10-Q  0000833444-21-000011
12    JCI  2021-04-30        10-Q  0000833444-21-000020
13    JCI  2021-07-30        10-Q  0000833444-21-000040
14    JCI  2022-02-02        10-Q  0000833444-22-000005
15    JCI  2022-05-04        10-Q  0000833444-22-000017
16    JCI  2022-08-04        10-Q  0000833444-22-000036
17    JCI  2023-02-01        10-Q  0000833444-23-000005
18    JCI  2023-05-05        10-Q  0000833444-23-000014
19    JCI  2023-08-02        10-Q  0000833444-23-000030
20    JCI  2024-01-30        10-Q  0000833444-24-000011
21    JCI  2024-05-01        10-Q  0000833444-24-000029
22    JCI  2024-07-31        10-Q  0000833444-24-000052
23   KLAC  2019-08-16        10-K  0000319201-19-000031
24   KLAC  2021-08-06        10-K  0000319201-21-000029
25   KLAC  2022-04-29        10-Q  0000319201-22-000012
26   KLAC  2022-08-05        10-K  0000319201-22-000023
27   KLAC  2023-08-04        10-K  0000319201-23-000031
32   SCHW  2021-05-07        10-Q  0000316709-21-000029
33   SCHW  2022-05-09        10-Q  0000316709-22-000018
34   SCHW  2022-11-08        10-Q  0000316709-22-000045
35   SCHW  2024-05-09        10-Q  0000316709-24-000044
36   SCHW  2024-08-08        10-Q  0000316709-24-000060
37   SCHW  2024-11-08        10-Q  0000316709-24-000069
38    USB  2020-05-07        10-Q  0001193125-20-136359
39    USB  2020-08-06        10-Q  0001193125-20-211979
40    USB  2020-11-05        10-Q  0001193125-20-286983
41    USB  2021-05-04        10-Q  0001193125-21-150169
42    USB  2021-08-03        10-Q  0001193125-21-234982
43    USB  2021-11-02        10-Q  0001193125-21-317037
44    USB  2022-05-03        10-Q  0001193125-22-138788
45    USB  2022-08-04        10-Q  0001193125-22-212040
46    USB  2022-11-01        10-Q  0001193125-22-275036
47    USB  2023-05-08        10-Q  0001193125-23-137980
48    USB  2023-08-07        10-Q  0001193125-23-204050
49    USB  2023-11-01        10-Q  0001193125-23-268341
50    USB  2024-05-01        10-Q  0000036104-24-000037
51    USB  2024-08-06        10-Q  0000036104-24-000052

In [27]:
results = []

for i, row in target_df.iterrows():
    result = repair_one_family_rule(row)
    results.append(result)

    if len(results) % 10 == 0 or len(results) == len(target_df):
        print(f"Processed {len(results)}/{len(target_df)}")

repair_log = pd.DataFrame(results)
repair_log.to_csv(REPAIR_LOG_CSV, index=False)

print("Family repair complete.")
display(repair_log["repair_status"].value_counts())
display(repair_log.head())

Processed 10/38
Processed 20/38
Processed 30/38
Processed 38/38
Family repair complete.

repair_status
NO_START     20
NO_END       14
BAD_START     3
OK            1
Name: count, dtype: int64

,ticker,filing_date,filing_type,accession_number,repair_status,primary_doc,repaired_filename
0,JCI,2020-07-31,10-Q,0000833444-20-000036,NO_START,q3ex311fy2010-q.htm,
1,JCI,2021-01-29,10-Q,0000833444-21-000011,NO_START,q1ex101fy2110-q.htm,
2,JCI,2021-04-30,10-Q,0000833444-21-000020,NO_START,q2ex104fy2110-q.htm,
3,JCI,2021-07-30,10-Q,0000833444-21-000040,NO_START,q3ex311fy2110-q.htm,
4,JCI,2022-02-02,10-Q,0000833444-22-000005,NO_START,q1ex101fy2210-q.htm,

In [28]:
TARGET_TICKERS = ["USB"]

target_df = repair_df.loc[repair_df["ticker"].isin(TARGET_TICKERS)].copy()

print("Target rows:", len(target_df))
display(target_df[["ticker", "filing_date", "filing_type", "accession_number"]])

Target rows: 14

   ticker filing_date filing_type      accession_number
38    USB  2020-05-07        10-Q  0001193125-20-136359
39    USB  2020-08-06        10-Q  0001193125-20-211979
40    USB  2020-11-05        10-Q  0001193125-20-286983
41    USB  2021-05-04        10-Q  0001193125-21-150169
42    USB  2021-08-03        10-Q  0001193125-21-234982
43    USB  2021-11-02        10-Q  0001193125-21-317037
44    USB  2022-05-03        10-Q  0001193125-22-138788
45    USB  2022-08-04        10-Q  0001193125-22-212040
46    USB  2022-11-01        10-Q  0001193125-22-275036
47    USB  2023-05-08        10-Q  0001193125-23-137980
48    USB  2023-08-07        10-Q  0001193125-23-204050
49    USB  2023-11-01        10-Q  0001193125-23-268341
50    USB  2024-05-01        10-Q  0000036104-24-000037
51    USB  2024-08-06        10-Q  0000036104-24-000052

In [29]:
FAMILY_RULES = {
    "USB": {
        "10-Q": {
            "start_patterns": [
                r"item\s*2[\.\-:\s]+management[' ]s discussion and analysis of financial condition and results of operations",
                r"management[' ]s discussion and analysis of financial condition and results of operations",
                r"management[' ]s discussion and analysis",
            ],
            "end_patterns": [
                r"item\s*3[\.\-:\s]+quantitative and qualitative disclosures about market risk",
                r"item\s*4[\.\-:\s]+controls and procedures",
                r"^item\s*3\b",
                r"^item\s*4\b",
            ],
        }
    }
}

In [30]:
results = []

for i, row in target_df.iterrows():
    result = repair_one_family_rule(row)
    results.append(result)

    if len(results) % 10 == 0 or len(results) == len(target_df):
        print(f"Processed {len(results)}/{len(target_df)}")

repair_log = pd.DataFrame(results)
repair_log.to_csv(REPAIR_LOG_CSV, index=False)

print("USB family repair complete.")
display(repair_log["repair_status"].value_counts())
display(repair_log.head())

Processed 10/14
Processed 14/14
USB family repair complete.

repair_status
NO_END    14
Name: count, dtype: int64

,ticker,filing_date,filing_type,accession_number,repair_status,primary_doc,repaired_filename
0,USB,2020-05-07,10-Q,0001193125-20-136359,NO_END,d897119d10q.htm,
1,USB,2020-08-06,10-Q,0001193125-20-211979,NO_END,d890129d10q.htm,
2,USB,2020-11-05,10-Q,0001193125-20-286983,NO_END,d947218d10q.htm,
3,USB,2021-05-04,10-Q,0001193125-21-150169,NO_END,d137164d10q.htm,
4,USB,2021-08-03,10-Q,0001193125-21-234982,NO_END,d913559d10q.htm,

In [31]:
ok_usb = repair_log.loc[repair_log["repair_status"] == "OK"].copy()
print("Recovered OK USB files:", len(ok_usb))
display(ok_usb)

Recovered OK USB files: 0

Empty DataFrame
Columns: [ticker, filing_date, filing_type, accession_number, repair_status, primary_doc, repaired_filename]
Index: []

In [32]:
def extract_usb_fallback_end(text):
    text = text.replace("\xa0", " ")
    text = text.replace("’", "'")
    low = text.lower()

    # start patterns
    start_patterns = [
        r"item\s*2[\.\-:\s]+management[' ]s discussion and analysis of financial condition and results of operations",
        r"management[' ]s discussion and analysis of financial condition and results of operations",
        r"management[' ]s discussion and analysis",
    ]

    starts = []
    for pat in start_patterns:
        for m in re.finditer(pat, low, flags=re.I):
            starts.append(m.start())

    starts = sorted(set(starts))
    if not starts:
        return None, "NO_START"

    doc_len = len(text)

    # prefer later starts to avoid TOC/reference hits
    starts = [s for s in starts if s > doc_len * 0.10] or starts

    # end patterns
    end_patterns = [
        r"item\s*3[\.\-:\s]+quantitative and qualitative disclosures about market risk",
        r"item\s*4[\.\-:\s]+controls and procedures",
        r"^item\s*3\b",
        r"^item\s*4\b",
    ]

    best_pair = None

    for s in starts:
        # first try explicit end patterns after s
        end_hits = []
        for pat in end_patterns:
            for m in re.finditer(pat, low[s:], flags=re.I | re.M):
                end_hits.append(s + m.start())

        end_hits = sorted(set(end_hits))

        # if no explicit end, fallback to next major item line
        if not end_hits:
            fallback = re.search(r"(?im)^item\s*(3|4)\b", low[s:])
            if fallback:
                end_hits = [s + fallback.start()]

        if not end_hits:
            continue

        e = end_hits[0]
        span = e - s

        if 3000 <= span <= 400000:
            best_pair = (s, e)
            break

    if best_pair is None:
        return None, "NO_END"

    s, e = best_pair
    mda = text[s:e].strip()

    wc = len(re.findall(r"\b[a-zA-Z]+\b", mda))
    if wc < 800:
        return None, "TOO_SHORT"

    first_500 = re.sub(r"\s+", " ", mda[:500]).lower()

    good = (
        ("item 2" in first_500 and "management's discussion" in first_500) or
        ("management's discussion and analysis" in first_500 and "financial condition" in first_500)
    )

    if not good:
        return None, "BAD_START"

    if (
        "table of contents" in first_500 or
        "under the heading" in first_500 or
        "refer to item" in first_500 or
        "see item" in first_500
    ):
        return None, "BAD_START"

    return mda, "OK"

In [33]:
def repair_one_usb_fallback(row, sleep_seconds=0.2):
    ticker = row["ticker"]
    cik = row["cik"]
    filing_date = row["filing_date"]
    filing_type = row["filing_type"]
    accession_number = row["accession_number"]

    out = {
        "ticker": ticker,
        "filing_date": filing_date,
        "filing_type": filing_type,
        "accession_number": accession_number,
        "repair_status": "",
        "primary_doc": "",
        "repaired_filename": ""
    }

    try:
        if pd.isna(cik):
            out["repair_status"] = "NO_CIK"
            return out

        idx = get_index_json(cik, accession_number)
        primary_doc = choose_primary_doc(idx, filing_type)
        if primary_doc is None:
            out["repair_status"] = "NO_PRIMARY_DOC"
            return out

        out["primary_doc"] = primary_doc

        html = download_filing_doc(cik, accession_number, primary_doc)
        text = html_to_text(html)

        mda_text, status = extract_usb_fallback_end(text)

        if status != "OK":
            out["repair_status"] = status
            return out

        fname = f"{ticker}_{filing_date}_{filing_type}_{accession_number}_USBFALLBACK.txt"
        with open(OUT_DIR / fname, "w", encoding="utf-8") as f:
            f.write(mda_text)

        out["repair_status"] = "OK"
        out["repaired_filename"] = fname

        time.sleep(sleep_seconds)
        return out

    except Exception as e:
        out["repair_status"] = f"ERROR: {str(e)[:120]}"
        return out

In [34]:
usb_df = repair_df.loc[repair_df["ticker"] == "USB"].copy()

print("USB rows:", len(usb_df))
display(usb_df[["ticker", "filing_date", "filing_type", "accession_number"]])

USB rows: 14

   ticker filing_date filing_type      accession_number
38    USB  2020-05-07        10-Q  0001193125-20-136359
39    USB  2020-08-06        10-Q  0001193125-20-211979
40    USB  2020-11-05        10-Q  0001193125-20-286983
41    USB  2021-05-04        10-Q  0001193125-21-150169
42    USB  2021-08-03        10-Q  0001193125-21-234982
43    USB  2021-11-02        10-Q  0001193125-21-317037
44    USB  2022-05-03        10-Q  0001193125-22-138788
45    USB  2022-08-04        10-Q  0001193125-22-212040
46    USB  2022-11-01        10-Q  0001193125-22-275036
47    USB  2023-05-08        10-Q  0001193125-23-137980
48    USB  2023-08-07        10-Q  0001193125-23-204050
49    USB  2023-11-01        10-Q  0001193125-23-268341
50    USB  2024-05-01        10-Q  0000036104-24-000037
51    USB  2024-08-06        10-Q  0000036104-24-000052

In [35]:
usb_results = []

for i, row in usb_df.iterrows():
    result = repair_one_usb_fallback(row)
    usb_results.append(result)

    if len(usb_results) % 10 == 0 or len(usb_results) == len(usb_df):
        print(f"Processed {len(usb_results)}/{len(usb_df)}")

usb_log = pd.DataFrame(usb_results)
usb_log.to_csv("/content/usb_fallback_log.csv", index=False)

print("USB fallback repair complete.")
display(usb_log["repair_status"].value_counts())
display(usb_log.head())

Processed 10/14
Processed 14/14
USB fallback repair complete.

repair_status
NO_END    14
Name: count, dtype: int64

,ticker,filing_date,filing_type,accession_number,repair_status,primary_doc,repaired_filename
0,USB,2020-05-07,10-Q,0001193125-20-136359,NO_END,d897119d10q.htm,
1,USB,2020-08-06,10-Q,0001193125-20-211979,NO_END,d890129d10q.htm,
2,USB,2020-11-05,10-Q,0001193125-20-286983,NO_END,d947218d10q.htm,
3,USB,2021-05-04,10-Q,0001193125-21-150169,NO_END,d137164d10q.htm,
4,USB,2021-08-03,10-Q,0001193125-21-234982,NO_END,d913559d10q.htm,

In [36]:
def inspect_item_lines_for_row(row):
    idx = get_index_json(row["cik"], row["accession_number"])
    primary_doc = choose_primary_doc(idx, row["filing_type"])
    html = download_filing_doc(row["cik"], row["accession_number"], primary_doc)
    text = html_to_text(html)

    lines = text.splitlines()
    item_lines = []

    for i, line in enumerate(lines):
        clean = re.sub(r"\s+", " ", line).strip()
        low = clean.lower()

        if re.search(r"\bitem\s*[1-9]\b", low) or "management's discussion" in low or "controls and procedures" in low:
            item_lines.append((i, clean))

    print("PRIMARY DOC:", primary_doc)
    print("=" * 120)
    for i, line in item_lines[:200]:
        print(f"{i:05d} | {line}")

    return text

In [37]:
usb_row0 = usb_df.iloc[0]
usb_text_debug = inspect_item_lines_for_row(usb_row0)

PRIMARY DOC: d897119d10q.htm
========================================================================================================================
00257 | 1) Management's Discussion and Analysis of Financial Condition and Results of Operations (Item 2)
00319 | f) Controls and Procedures (Item 4)
00329 | 2) Quantitative and Qualitative Disclosures About Market Risk/Corporate Risk Profile (Item 3)
00439 | 4) Financial Statements (Item 1)
00453 | 1) Legal Proceedings (Item 1)
00473 | 3) Unregistered Sales of Equity Securities and Use of Proceeds (Item 2)
00483 | 4) Exhibits (Item 6)
01981 | Management's Discussion and Analysis
03676 | In addition, credit quality ratings as defined by the Company, are an important part of the Company's overall credit risk management and evaluation of its allowance for credit losses. Loans with a pass rating represent those loans not classified on the Company's rating scale for problem credits, as minimal risk has been identified. Loans with a special mention or classified rating, including loans that are 90 days or more past due and still accruing, nonaccrual loans, those loans considered troubled debt restructurings (“TDRs”), and loans in a junior lien position that are current but are behind a modified or delinquent loan in a first lien position, encompass all loans held by the Company that it considers to have a potential or well-defined weakness that may put full collection of contractual cash flows at risk. The Company's internal credit quality ratings for consumer loans are primarily based on delinquency and nonperforming status, except for a limited population of larger loans within those portfolios that are individually evaluated. For this limited population, the determination of the internal credit quality rating may also consider collateral value and customer cash flows. Refer to Note 4 in the Notes to Consolidated Financial Statements for further discussion of the Company's loan portfolios including internal credit quality ratings. In addition, refer to “Management's Discussion and Analysis — Credit Risk Management” in the Company's Annual Report on
10998 | The Company manages its risk to changes in the residual value of leased vehicles, office and business equipment, and other assets through disciplined residual valuation setting at the inception of a lease, diversification of its leased assets, regular residual asset valuation reviews and monitoring of residual value gains or losses upon the disposition of assets. As of March 31, 2020, no significant change in the amount of residual values or concentration of the portfolios had occurred since December 31, 2019. Refer to “Management's Discussion and Analysis — Residual Value Risk Management” in the Company's Annual Report on
11003 | Operational risk is inherent in all business activities, and the management of this risk is important to the achievement of the Company's objectives. Business lines have direct and primary responsibility and accountability for identifying, controlling, and monitoring operational risks embedded in their business activities. The Company maintains a system of controls with the objective of providing proper transaction authorization and execution, proper system operations, proper oversight of third parties with whom it does business, safeguarding of assets from misuse or theft, and ensuring the reliability and security of financial and other data. Refer to “Management's Discussion and Analysis — Operational Risk Management” in the Company's Annual Report on
11008 | The Company may suffer legal or regulatory sanctions, material financial loss, or damage to its reputation through failure to comply with laws, regulations, rules, standards of good practice, and codes of conduct, including those related to compliance with Bank Secrecy Act/anti-money laundering requirements, sanctions compliance requirements as administered by the Office of Foreign Assets Control, consumer protection and other requirements. The Company has controls and processes in place for the assessment, identification, monitoring, management and reporting of compliance risks and issues. Refer to “Management's Discussion and Analysis — Compliance Risk Management” in the Company's Annual Report on
12062 | Refer to “Management's Discussion and Analysis — Liquidity Risk Management” in the Company's Annual Report on
12710 | Refer to “Management's Discussion and Analysis — Capital Management” in the Company's Annual Report on
19362 | Management's evaluation of the appropriate allowance for credit losses is often the most critical of all the accounting estimates for a banking institution. It is an inherently subjective process impacted by many factors as discussed throughout the Management's Discussion and Analysis section of this Quarterly Report on Form 10-Q. Prior to January 1, 2020, the allowance for credit losses was established to provide for probable and estimable losses incurred in the Company's credit portfolio. Effective January 1, 2020, the Company adopted new accounting guidance which changed previous impairment recognition to a model that is based
19442 | Accounting policies related to fair value estimates, MSRs, and income taxes are discussed in detail in “Management's Discussion and Analysis — Critical Accounting Policies” and the Notes to Consolidated Financial Statements in the Company's Annual Report on
19446 | CONTROLS AND PROCEDURES
19448 | Under the supervision and with the participation of the Company's management, including its principal executive officer and principal financial officer, the Company has evaluated the effectiveness of the design and operation of its disclosure controls and procedures (as defined in
19452 | under the Securities Exchange Act of 1934 (the “Exchange Act”)). Based upon this evaluation, the principal executive officer and principal financial officer have concluded that, as of the end of the period covered by this report, the Company's disclosure controls and procedures were effective.
63716 | Item 1. Legal Proceedings
63717 | — See the information set forth in Note 15 in the Notes to Consolidated Financial Statements under Part I, Item 1 of this Report, which is incorporated herein by reference.
63813 | Item 2. Unregistered Sales of Equity Securities and Use of Proceeds
63814 | — Refer to the “Capital Management” section within Management's Discussion and Analysis in Part I, Item 2 of this Report for information regarding shares repurchased by the Company during the first quarter of 2020.
63842 | Item 6. Exhibits
64144 | The registrant's other certifying officers and I are responsible for establishing and maintaining disclosure controls and procedures (as defined in Exchange Act Rules
64166 | designed such disclosure controls and procedures, or caused such disclosure controls and procedures to be designed under our supervision, to ensure that material information relating to the registrant, including its consolidated subsidiaries, is made known to us by others within those entities, particularly during the period in which this report is being prepared;
64194 | evaluated the effectiveness of the registrant's disclosure controls and procedures and presented in this report our conclusions about the effectiveness of the disclosure controls and procedures, as of the end of the period covered by this report based on such evaluation; and
64359 | The registrant's other certifying officers and I are responsible for establishing and maintaining disclosure controls and procedures (as defined in Exchange Act Rules
64381 | designed such disclosure controls and procedures, or caused such disclosure controls and procedures to be designed under our supervision, to ensure that material information relating to the registrant, including its consolidated subsidiaries, is made known to us by others within those entities, particularly during the period in which this report is being prepared;
64409 | evaluated the effectiveness of the registrant's disclosure controls and procedures and presented in this report our conclusions about the effectiveness of the disclosure controls and procedures, as of the end of the period covered by this report based on such evaluation; and

In [38]:
patterns = [
    r"item\s*3",
    r"item\s*4",
    r"quantitative and qualitative disclosures about market risk",
    r"controls and procedures",
]

for pat in patterns:
    print("\nPATTERN:", pat)
    for m in re.finditer(pat, usb_text_debug, flags=re.I):
        start = max(0, m.start() - 120)
        end = min(len(usb_text_debug), m.start() + 220)
        snippet = usb_text_debug[start:end].replace("\n", " ")
        print(snippet)
        print("-" * 100)
        break

PATTERN: item\s*3
Procedures (Item 4)        32     2) Quantitative and Qualitative Disclosures About Market Risk/Corporate Risk Profile (Item 3)         7     a) Overview        7     b) Credit Risk Management        9     c) Residual Value Risk Management        20     d) Operational Risk Management        20     e) Compliance Risk Management        20
----------------------------------------------------------------------------------------------------

PATTERN: item\s*4
)  Non-GAAP  Financial Measures        29     e) Critical Accounting Policies        30     f) Controls and Procedures (Item 4)        32     2) Quantitative and Qualitative Disclosures About Market Risk/Corporate Risk Profile (Item 3)         7     a) Overview        7     b) Credit Risk Management        9     c) Residual Value Risk Man
----------------------------------------------------------------------------------------------------

PATTERN: quantitative and qualitative disclosures about market risk
asures        29     e) Critical Accounting Policies        30     f) Controls and Procedures (Item 4)        32     2) Quantitative and Qualitative Disclosures About Market Risk/Corporate Risk Profile (Item 3)         7     a) Overview        7     b) Credit Risk Management        9     c) Residual Value Risk Management        20     d)
----------------------------------------------------------------------------------------------------

PATTERN: controls and procedures
t Analysis        6     d)  Non-GAAP  Financial Measures        29     e) Critical Accounting Policies        30     f) Controls and Procedures (Item 4)        32     2) Quantitative and Qualitative Disclosures About Market Risk/Corporate Risk Profile (Item 3)         7     a) Overview        7     b) Credit Risk Management        9     c
----------------------------------------------------------------------------------------------------

In [39]:
for pat in [
    r"item\s*2",
    r"management[' ]s discussion and analysis",
    r"management[' ]s discussion and analysis of financial condition and results of operations",
]:
    print("\nPATTERN:", pat)
    for m in re.finditer(pat, usb_text_debug, flags=re.I):
        start = max(0, m.start() - 120)
        end = min(len(usb_text_debug), m.start() + 220)
        snippet = usb_text_debug[start:end].replace("\n", " ")
        print(snippet)
        print("-" * 100)
        break

PATTERN: item\s*2
I — Financial Information     1) Management's Discussion and Analysis of Financial Condition and Results of Operations (Item 2)        3     a) Overview        3     b) Statement of Income Analysis        3     c) Balance Sheet Analysis        6     d)  Non-GAAP  Financial Measures        29     e) Critical Accounting Policies        30
----------------------------------------------------------------------------------------------------

PATTERN: management[' ]s discussion and analysis
  Table of Contents   Table of Contents and  Form 10-Q  Cross Reference Index     Part I — Financial Information     1) Management's Discussion and Analysis of Financial Condition and Results of Operations (Item 2)        3     a) Overview        3     b) Statement of Income Analysis        3     c) Balance Sheet Analysis        6     d)
----------------------------------------------------------------------------------------------------

PATTERN: management[' ]s discussion and analysis of financial condition and results of operations
  Table of Contents   Table of Contents and  Form 10-Q  Cross Reference Index     Part I — Financial Information     1) Management's Discussion and Analysis of Financial Condition and Results of Operations (Item 2)        3     a) Overview        3     b) Statement of Income Analysis        3     c) Balance Sheet Analysis        6     d)
----------------------------------------------------------------------------------------------------

In [40]:
def extract_usb_real(text):
    text = text.replace("\xa0", " ")
    text = text.replace("’", "'")

    low = text.lower()

    # real start candidates: later MD&A, not TOC
    start_matches = []
    for m in re.finditer(r"management[' ]s discussion and analysis", low, flags=re.I):
        start_matches.append(m.start())

    if not start_matches:
        return None, "NO_START"

    # reject early TOC matches by keeping only later occurrences
    doc_len = len(text)
    start_matches = [s for s in start_matches if s > doc_len * 0.10] or start_matches

    # end candidates based on actual USB text
    end_matches = []
    for pat in [
        r"controls and procedures",
        r"item\s*4[\.\-:\s]+controls and procedures",
        r"^controls and procedures$",
    ]:
        for m in re.finditer(pat, low, flags=re.I | re.M):
            end_matches.append(m.start())

    end_matches = sorted(set(end_matches))

    if not end_matches:
        return None, "NO_END"

    best_pair = None

    for s in start_matches:
        valid_ends = [e for e in end_matches if e > s]
        if not valid_ends:
            continue

        e = valid_ends[0]
        span = e - s

        if 3000 <= span <= 400000:
            best_pair = (s, e)
            break

    if best_pair is None:
        return None, "NO_VALID_SPAN"

    s, e = best_pair
    mda = text[s:e].strip()

    wc = len(re.findall(r"\b[a-zA-Z]+\b", mda))
    if wc < 800:
        return None, "TOO_SHORT"

    first_500 = re.sub(r"\s+", " ", mda[:500]).lower()

    # reject TOC-style starts
    if (
        "table of contents" in first_500 or
        "cross reference index" in first_500 or
        "part i — financial information" in first_500 or
        "item 2)" in first_500
    ):
        return None, "BAD_START"

    # accept later narrative MD&A start
    if "management's discussion and analysis" not in first_500:
        return None, "BAD_START"

    return mda, "OK"

In [41]:
def repair_one_usb_real(row, sleep_seconds=0.2):
    ticker = row["ticker"]
    cik = row["cik"]
    filing_date = row["filing_date"]
    filing_type = row["filing_type"]
    accession_number = row["accession_number"]

    out = {
        "ticker": ticker,
        "filing_date": filing_date,
        "filing_type": filing_type,
        "accession_number": accession_number,
        "repair_status": "",
        "primary_doc": "",
        "repaired_filename": ""
    }

    try:
        if pd.isna(cik):
            out["repair_status"] = "NO_CIK"
            return out

        idx = get_index_json(cik, accession_number)
        primary_doc = choose_primary_doc(idx, filing_type)

        if primary_doc is None:
            out["repair_status"] = "NO_PRIMARY_DOC"
            return out

        out["primary_doc"] = primary_doc

        html = download_filing_doc(cik, accession_number, primary_doc)
        text = html_to_text(html)

        mda_text, status = extract_usb_real(text)

        if status != "OK":
            out["repair_status"] = status
            return out

        fname = f"{ticker}_{filing_date}_{filing_type}_{accession_number}_USBREAL.txt"
        with open(OUT_DIR / fname, "w", encoding="utf-8") as f:
            f.write(mda_text)

        out["repair_status"] = "OK"
        out["repaired_filename"] = fname

        time.sleep(sleep_seconds)
        return out

    except Exception as e:
        out["repair_status"] = f"ERROR: {str(e)[:120]}"
        return out

In [42]:
usb_df = repair_df.loc[repair_df["ticker"] == "USB"].copy()

print("USB rows:", len(usb_df))
display(usb_df[["ticker", "filing_date", "filing_type", "accession_number"]])

USB rows: 14

   ticker filing_date filing_type      accession_number
38    USB  2020-05-07        10-Q  0001193125-20-136359
39    USB  2020-08-06        10-Q  0001193125-20-211979
40    USB  2020-11-05        10-Q  0001193125-20-286983
41    USB  2021-05-04        10-Q  0001193125-21-150169
42    USB  2021-08-03        10-Q  0001193125-21-234982
43    USB  2021-11-02        10-Q  0001193125-21-317037
44    USB  2022-05-03        10-Q  0001193125-22-138788
45    USB  2022-08-04        10-Q  0001193125-22-212040
46    USB  2022-11-01        10-Q  0001193125-22-275036
47    USB  2023-05-08        10-Q  0001193125-23-137980
48    USB  2023-08-07        10-Q  0001193125-23-204050
49    USB  2023-11-01        10-Q  0001193125-23-268341
50    USB  2024-05-01        10-Q  0000036104-24-000037
51    USB  2024-08-06        10-Q  0000036104-24-000052

In [43]:
usb_results = []

for i, row in usb_df.iterrows():
    result = repair_one_usb_real(row)
    usb_results.append(result)

    if len(usb_results) % 10 == 0 or len(usb_results) == len(usb_df):
        print(f"Processed {len(usb_results)}/{len(usb_df)}")

usb_log = pd.DataFrame(usb_results)
usb_log.to_csv("/content/usb_real_log.csv", index=False)

print("USB real extraction complete.")
display(usb_log["repair_status"].value_counts())
display(usb_log.head())

Processed 10/14
Processed 14/14
USB real extraction complete.

repair_status
OK           13
BAD_START     1
Name: count, dtype: int64

,ticker,filing_date,filing_type,accession_number,repair_status,primary_doc,repaired_filename
0,USB,2020-05-07,10-Q,0001193125-20-136359,OK,d897119d10q.htm,USB_2020-05-07_10-Q_0001193125-20-136359_USBRE...
1,USB,2020-08-06,10-Q,0001193125-20-211979,OK,d890129d10q.htm,USB_2020-08-06_10-Q_0001193125-20-211979_USBRE...
2,USB,2020-11-05,10-Q,0001193125-20-286983,OK,d947218d10q.htm,USB_2020-11-05_10-Q_0001193125-20-286983_USBRE...
3,USB,2021-05-04,10-Q,0001193125-21-150169,OK,d137164d10q.htm,USB_2021-05-04_10-Q_0001193125-21-150169_USBRE...
4,USB,2021-08-03,10-Q,0001193125-21-234982,BAD_START,d913559d10q.htm,

In [44]:
ok_usb = usb_log.loc[usb_log["repair_status"] == "OK"].copy()
print("Recovered OK USB files:", len(ok_usb))
display(ok_usb)

Recovered OK USB files: 13

,ticker,filing_date,filing_type,accession_number,repair_status,primary_doc,repaired_filename
0,USB,2020-05-07,10-Q,0001193125-20-136359,OK,d897119d10q.htm,USB_2020-05-07_10-Q_0001193125-20-136359_USBRE...
1,USB,2020-08-06,10-Q,0001193125-20-211979,OK,d890129d10q.htm,USB_2020-08-06_10-Q_0001193125-20-211979_USBRE...
2,USB,2020-11-05,10-Q,0001193125-20-286983,OK,d947218d10q.htm,USB_2020-11-05_10-Q_0001193125-20-286983_USBRE...
3,USB,2021-05-04,10-Q,0001193125-21-150169,OK,d137164d10q.htm,USB_2021-05-04_10-Q_0001193125-21-150169_USBRE...
5,USB,2021-11-02,10-Q,0001193125-21-317037,OK,d219476d10q.htm,USB_2021-11-02_10-Q_0001193125-21-317037_USBRE...
6,USB,2022-05-03,10-Q,0001193125-22-138788,OK,d306477d10q.htm,USB_2022-05-03_10-Q_0001193125-22-138788_USBRE...
7,USB,2022-08-04,10-Q,0001193125-22-212040,OK,d322057d10q.htm,USB_2022-08-04_10-Q_0001193125-22-212040_USBRE...
8,USB,2022-11-01,10-Q,0001193125-22-275036,OK,d245647d10q.htm,USB_2022-11-01_10-Q_0001193125-22-275036_USBRE...
9,USB,2023-05-08,10-Q,0001193125-23-137980,OK,d796135d10q.htm,USB_2023-05-08_10-Q_0001193125-23-137980_USBRE...
10,USB,2023-08-07,10-Q,0001193125-23-204050,OK,d425808d10q.htm,USB_2023-08-07_10-Q_0001193125-23-204050_USBRE...
11,USB,2023-11-01,10-Q,0001193125-23-268341,OK,d542369d10q.htm,USB_2023-11-01_10-Q_0001193125-23-268341_USBRE...
12,USB,2024-05-01,10-Q,0000036104-24-000037,OK,usb-20240331.htm,USB_2024-05-01_10-Q_0000036104-24-000037_USBRE...
13,USB,2024-08-06,10-Q,0000036104-24-000052,OK,usb-20240630.htm,USB_2024-08-06_10-Q_0000036104-24-000052_USBRE...

In [45]:
for i in range(len(ok_usb)):
    fname = ok_usb.iloc[i]["repaired_filename"]
    print(f"\n### Reviewing USB row {i}")
    preview_repaired_file(fname)

### Reviewing USB row 0
========================================================================================================================
FILE: USB_2020-05-07_10-Q_0001193125-20-136359_USBREAL.txt
========================================================================================================================

--- START PREVIEW ---

Management's Discussion and Analysis — Credit Risk Management” in the Company's Annual Report on
Form 10-K
 for the year ended December 31, 2019, for a more detailed discussion on credit risk management processes.

The Company manages its credit risk, in part, through diversification of its loan portfolio which is achieved through limit setting by product type criteria, such as industry, and identification of credit concentrations. As part of its normal business activities, the Company offers a broad array of lending products. The Company categorizes its loan portfolio into two segments, which is the level at which it develops and documents a systematic methodology to determine the allowance for credit losses. The Company's two loan portfolio segments are commercial lending and consumer lending.

The commercial lending segment includes loans and leases made to small business, middle market, large corporate, commercial real estate, financial institution,
non-profit
 and public sector customers. Key risk characteristics relevant to commercial lending segment loans include the industry and geography of the borrower's business, purpose of the loan, repayment source, borrower's debt capacity and financial flexibility, loan covenants, and nature of pledged collateral, if any. These risk characteristics, among others, are considered in determining estimates about the likelihood of default by the borrowers and the severity of loss in the event of default. The Company considers these risk characteristics in assigning internal risk ratings to, or forecasting losses on, these loans, which are the significant factors in determining the allowance for credit losses for loans in the commercial lending segment.

The consumer lending segment represents loans and leases made to consumer customers, including residential mortgages, credit card loans, and other retail loans such as revolving consumer lines, auto loans and leases, home equity loans and lines, and student loans, a
run-off
 portfolio. Home equity or second mortgage loans are junior lien
closed-end
 accounts fully disbursed at origination. These loans typically are fixed rate loans, secured by residential real estate, with a
10-
 or
15-year
 fixed payment amortization schedule. Home equity lines are revolving accounts giving the borrower the ability to draw and repay balances repeatedly, up to a maximum commitment, and are secured by residential real estate. These include accounts in either a first or ju

--- END PREVIEW ---

the allowance for credit losses, these sensitivity analyses do not necessarily reflect the nature and extent of future changes in the allowance for credit










U.S. Bancorp



31










Table of Contents



losses. They are intended to provide insights into the impact of adverse changes in risk rating and loss model estimates and do not imply any expectation of future deterioration in the risk rating or loss rates. Given current processes employed by the Company, management believes the risk ratings and loss model estimates currently assigned are appropriate. It is possible that others, given the same information, may at any point in time reach different reasonable conclusions that could be significant to the Company's financial statements. Refer to the “Analysis and Determination of the Allowance for Credit Losses” section for further information.

Accounting policies related to fair value estimates, MSRs, and income taxes are discussed in detail in “Management's Discussion and Analysis — Critical Accounting Policies” and the Notes to Consolidated Financial Statements in the Company's Annual Report on
Form 10-K
 for the year ended December 31, 2019.

Word count: 13649
========================================================================================================================

### Reviewing USB row 1
========================================================================================================================
FILE: USB_2020-08-06_10-Q_0001193125-20-211979_USBREAL.txt
========================================================================================================================

--- START PREVIEW ---

Management's Discussion and Analysis — Credit Risk Management” in the Company's Annual Report on
Form 10-K
 for the year ended December 31, 2019, for a more detailed discussion on credit risk management processes.

The Company manages its credit risk, in part, through diversification of its loan portfolio which is achieved through limit setting by product type criteria, such as industry, and identification of credit concentrations. As part of its normal business activities, the Company offers a broad array of lending products. The Company categorizes its loan portfolio into two segments, which is the level at which it develops and documents a systematic methodology to determine the allowance for credit losses. The Company's two loan portfolio segments are commercial lending and consumer lending.

The commercial lending segment includes loans and leases made to small business, middle market, large corporate, commercial real estate, financial institution,
non-profit
 and public sector customers. Key risk characteristics relevant to commercial lending segment loans include the industry and geography of the borrower's business, purpose of the loan, repayment source, borrower's debt capacity and financial flexibility, loan covenants, and nature of pledged collateral, if any. These risk characteristics, among others, are considered in determining estimates about the likelihood of default by the borrowers and the severity of loss in the event of default. The Company considers these risk characteristics in assigning internal risk ratings to, or forecasting losses on, these loans, which are the significant factors in determining the allowance for credit losses for loans in the commercial lending segment.

The consumer lending segment represents loans and leases made to consumer customers, including residential mortgages, credit card loans, and other retail loans such as revolving consumer lines, auto loans and leases, home equity loans and lines, and student loans, a
run-off
 portfolio. Home equity or second mortgage loans are junior lien
closed-end
 accounts fully disbursed at origination. These loans typically are fixed rate loans, secured by residential real estate, with a
10-
 or
15-year
 fixed payment amortization schedule. Home equity lines are revolving accounts giving the borrower the ability to draw and repay balances repeatedly, up to a maximum commitment, and are secured by residential real estate. These include accounts in either a first or ju

--- END PREVIEW ---

termining the allowance for credit





34



U.S. Bancorp










Table of Contents



losses, these sensitivity analyses do not necessarily reflect the nature and extent of future changes in the allowance for credit losses. They are intended to provide insights into the impact of adverse changes in risk rating and loss model estimates and do not imply any expectation of future deterioration in the risk rating or loss rates. Given current processes employed by the Company, management believes the risk ratings and loss model estimates currently assigned are appropriate. It is possible that others, given the same information, may at any point in time reach different reasonable conclusions that could be significant to the Company's financial statements. Refer to the “Analysis and Determination of the Allowance for Credit Losses” section for further information.

Accounting policies related to fair value estimates, MSRs, and income taxes are discussed in detail in “Management's Discussion and Analysis — Critical Accounting Policies” and the Notes to Consolidated Financial Statements in the Company's Annual Report on Form 10-K for the year ended December 31, 2019.

Word count: 14732
========================================================================================================================

### Reviewing USB row 2
========================================================================================================================
FILE: USB_2020-11-05_10-Q_0001193125-20-286983_USBREAL.txt
========================================================================================================================

--- START PREVIEW ---

Management's Discussion and Analysis — Credit Risk Management” in the Company's Annual Report on
Form 10-K
 for the year ended December 31, 2019, for a more detailed discussion on credit risk management processes.

The Company manages its credit risk, in part, through diversification of its loan portfolio which is achieved through limit setting by product type criteria, such as industry, and identification of credit concentrations. As part of its normal business activities, the Company offers a broad array of lending products. The Company categorizes its loan portfolio into two segments, which is the level at which it develops and documents a systematic methodology to determine the allowance for credit losses. The Company's two loan portfolio segments are commercial lending and consumer lending.



The commercial lending segment includes loans and leases made to small business, middle market, large corporate, commercial real estate, financial institution,
non-profit
 and public sector customers. Key risk characteristics relevant to commercial lending segment loans include the industry and geography of the borrower's business, purpose of the loan, repayment source, borrower's debt capacity and financial flexibility, loan covenants, and nature of pledged collateral, if any, as well as macroeconomic factors such as unemployment rates, gross domestic product levels, corporate bond spreads and long-term interest rates, all of which have been impacted by the COVID-19 pandemic. These risk characteristics, among others, are considered in determining estimates about the likelihood of default by the borrowers and the severity of loss in the event of default. The Company considers these risk characteristics in assigning internal risk ratings to, or forecasting losses on, these loans, which are the significant factors in determining the allowance for credit losses for loans in the commercial lending segment.



The consumer lending segment represents loans and leases made to consumer customers, including residential mortgages, credit card loans, and other retail loans such as revolving consumer lines, auto loans and leases, home equity loans and lines, and student loans, a
run-off
 portfolio. Home equity or second mortgage loans are junior lien
closed-end
 accounts fully disbursed at origination. These loans typically are fixed rate loans, secured by residential real estate, with a
10-
 or
15-year
 fixed payment amortization schedule. Home equity lines a

--- END PREVIEW ---

cause several quantitative and qualitative factors are considered in determining the allowance for credit losses, these sensitivity analyses do not necessarily reflect the nature and extent of future changes in the allowance for credit losses. They are intended to provide insights into the impact of adverse changes in risk rating and loss model estimates and do not imply any expectation of future deterioration in the risk rating or loss rates. Given current processes employed by the Company, management believes the risk ratings and loss model estimates currently assigned are appropriate. It is possible that others, given the same information, may at any point in time reach different reasonable conclusions that could be significant to the Company's financial statements. Refer to the “Analysis and Determination of the Allowance for Credit Losses” section for further information.

Accounting policies related to fair value estimates, MSRs, and income taxes are discussed in detail in “Management's Discussion and Analysis — Critical Accounting Policies” and the Notes to Consolidated Financial Statements in the Company's Annual Report on
Form 10-K
 for the year ended December 31, 2019.

Word count: 15002
========================================================================================================================

### Reviewing USB row 3
========================================================================================================================
FILE: USB_2021-05-04_10-Q_0001193125-21-150169_USBREAL.txt
========================================================================================================================

--- START PREVIEW ---

Management's Discussion and Analysis — Credit Risk Management” in the Company's Annual Report on
Form 10-K
 for the year ended December 31, 2020, for a more detailed discussion on credit risk management processes.

The Company manages its credit risk, in part, through diversification of its loan portfolio which is achieved through limit setting by product type criteria, such as industry, and identification of credit concentrations. As part of its normal business activities, the Company offers a broad array of lending products. The Company categorizes its loan portfolio into two segments, which is the level at which it develops and documents a systematic methodology to determine the allowance for credit losses. The Company's two loan portfolio segments are commercial lending and consumer lending.

The commercial lending segment includes loans and leases made to small business, middle market, large corporate, commercial real estate, financial institution,
non-profit
 and public sector customers. Key risk characteristics relevant to commercial lending segment loans include the industry and geography of the borrower's business, purpose of the loan, repayment source, borrower's debt capacity and financial flexibility, loan covenants, and nature of pledged collateral, if any, as well as macroeconomic factors such as unemployment rates, gross domestic product levels, corporate bond spreads and long-term interest rates, all of which have been impacted by the
COVID-19
 pandemic. These risk characteristics, among others, are considered in determining estimates about the likelihood of default by the borrowers and the severity of loss in the event of default. The Company considers these risk characteristics in assigning internal risk ratings to, or forecasting losses on, these loans, which are the significant factors in determining the allowance for credit losses for loans in the commercial lending segment.

The consumer lending segment represents loans and leases made to consumer customers, including residential mortgages, credit card loans, and other retail loans such as revolving consumer lines, auto loans and leases, home equity loans and lines, and student loans, a
run-off
 portfolio. Home equity or second mortgage loans are junior lien
closed-end
 accounts fully disbursed at origination. These loans typically are fixed rate loans, secured by residential real estate, with a
10-
 or
15-year
 fixed payment amortization schedule. Home equity lines are r

--- END PREVIEW ---

ithin the banking industry. The preparation of financial statements in conformity with GAAP requires management to make estimates and assumptions. The Company's financial position and results of operations can be affected by these estimates and assumptions, which are integral to understanding the Company's financial statements. Critical accounting policies are those policies management believes are the most important to the portrayal of the Company's financial condition and results, and require management to make estimates that are difficult, subjective or complex. Most accounting policies are not considered by management to be critical accounting policies. Management has discussed the development and the selection of critical accounting policies with the Company's Audit Committee. Those policies considered to be critical accounting policies relate to the allowance for credit losses, fair value estimates, MSRs, and income taxes. These accounting policies are discussed in detail in “Management's Discussion and Analysis — Critical Accounting Policies” and the Notes to Consolidated Financial Statements in the Company's Annual Report on
Form 10-K
 for the year ended December 31, 2020.

Word count: 13613
========================================================================================================================

### Reviewing USB row 4
========================================================================================================================
FILE: USB_2021-11-02_10-Q_0001193125-21-317037_USBREAL.txt
========================================================================================================================

--- START PREVIEW ---

Management's Discussion and Analysis — Credit Risk Management” in the Company's Annual Report on
Form 10-K
 for the year ended December 31, 2020, for a more detailed discussion on credit risk management processes.

The Company manages its credit risk, in part, through diversification of its loan portfolio which is achieved through limit setting by product type criteria, such as industry, and identification of credit concentrations. As part of its normal business activities, the Company offers a broad array of lending products. The Company categorizes its loan portfolio into two segments, which is the level at which it develops and documents a systematic methodology to determine the allowance for credit losses. The Company's two loan portfolio segments are commercial lending and consumer lending.

The commercial lending segment includes loans and leases made to small business, middle market, large corporate, commercial real estate, financial institution,
non-profit
 and public sector customers. Key risk characteristics relevant to commercial lending segment loans include the industry and geography of the borrower's business, purpose of the loan, repayment source, borrower's debt capacity and financial flexibility, loan covenants, and nature of pledged collateral, if any, as well as macroeconomic factors such as unemployment rates, gross domestic product levels, corporate bond spreads and long-term interest rates, all of which have been impacted by the
COVID-19
 pandemic. These risk characteristics, among others, are considered in determining estimates about the likelihood of default by the borrowers and the severity of loss in the event of default. The Company considers these risk characteristics in assigning internal risk ratings to, or forecasting losses on, these loans, which are the significant factors in determining the allowance for credit losses for loans in the commercial lending segment.

The consumer lending segment represents loans and leases made to consumer customers, including residential mortgages, credit card loans, and other retail loans such as revolving consumer lines, auto loans and leases, home equity loans and lines, and student loans, a
run-off
 portfolio. Home equity or second mortgage loans are junior lien
closed-end
 accounts fully disbursed at origination. These loans typically are fixed rate loans, secured by residential real estate, with a
10-
 or
15-year
 fixed payment amortization schedule. Home equity lines are r

--- END PREVIEW ---


In [46]:
ok_usb = usb_log.loc[
    usb_log["repair_status"] == "OK",
    ["ticker", "filing_date", "filing_type", "accession_number", "repaired_filename"]
].copy()

print("USB OK files:", len(ok_usb))
display(ok_usb)

USB OK files: 13

,ticker,filing_date,filing_type,accession_number,repaired_filename
0,USB,2020-05-07,10-Q,0001193125-20-136359,USB_2020-05-07_10-Q_0001193125-20-136359_USBRE...
1,USB,2020-08-06,10-Q,0001193125-20-211979,USB_2020-08-06_10-Q_0001193125-20-211979_USBRE...
2,USB,2020-11-05,10-Q,0001193125-20-286983,USB_2020-11-05_10-Q_0001193125-20-286983_USBRE...
3,USB,2021-05-04,10-Q,0001193125-21-150169,USB_2021-05-04_10-Q_0001193125-21-150169_USBRE...
5,USB,2021-11-02,10-Q,0001193125-21-317037,USB_2021-11-02_10-Q_0001193125-21-317037_USBRE...
6,USB,2022-05-03,10-Q,0001193125-22-138788,USB_2022-05-03_10-Q_0001193125-22-138788_USBRE...
7,USB,2022-08-04,10-Q,0001193125-22-212040,USB_2022-08-04_10-Q_0001193125-22-212040_USBRE...
8,USB,2022-11-01,10-Q,0001193125-22-275036,USB_2022-11-01_10-Q_0001193125-22-275036_USBRE...
9,USB,2023-05-08,10-Q,0001193125-23-137980,USB_2023-05-08_10-Q_0001193125-23-137980_USBRE...
10,USB,2023-08-07,10-Q,0001193125-23-204050,USB_2023-08-07_10-Q_0001193125-23-204050_USBRE...
11,USB,2023-11-01,10-Q,0001193125-23-268341,USB_2023-11-01_10-Q_0001193125-23-268341_USBRE...
12,USB,2024-05-01,10-Q,0000036104-24-000037,USB_2024-05-01_10-Q_0000036104-24-000037_USBRE...
13,USB,2024-08-06,10-Q,0000036104-24-000052,USB_2024-08-06_10-Q_0000036104-24-000052_USBRE...

In [47]:
import re
import pandas as pd
from pathlib import Path

USB_DIR = OUT_DIR  # this should already point to your USB repaired txt folder

def read_text_safe(path):
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        return f.read()

def word_count_alpha(text):
    return len(re.findall(r"\b[a-zA-Z]+\b", text))

review_rows = []

for _, row in ok_usb.iterrows():
    path = USB_DIR / row["repaired_filename"]
    text = read_text_safe(path)

    review_rows.append({
        "ticker": row["ticker"],
        "filing_date": row["filing_date"],
        "filing_type": row["filing_type"],
        "accession_number": row["accession_number"],
        "repaired_filename": row["repaired_filename"],
        "word_count": word_count_alpha(text),
        "first_300_chars": text[:300].replace("\n", " "),
        "first_1000_chars": text[:1000].replace("\n", " "),
        "last_500_chars": text[-500:].replace("\n", " "),
        "manual_label": "",
        "notes": "",
    })

usb_review_df = pd.DataFrame(review_rows)

print("Rows in USB review CSV:", len(usb_review_df))
display(usb_review_df)

Rows in USB review CSV: 13

,ticker,filing_date,filing_type,accession_number,repaired_filename,word_count,first_300_chars,first_1000_chars,last_500_chars,manual_label,notes
0,USB,2020-05-07,10-Q,0001193125-20-136359,USB_2020-05-07_10-Q_0001193125-20-136359_USBRE...,13649,Management's Discussion and Analysis — Credit ...,Management's Discussion and Analysis — Credit ...,le conclusions that could be significant to th...,,
1,USB,2020-08-06,10-Q,0001193125-20-211979,USB_2020-08-06_10-Q_0001193125-20-211979_USBRE...,14732,Management's Discussion and Analysis — Credit ...,Management's Discussion and Analysis — Credit ...,able conclusions that could be significant to ...,,
2,USB,2020-11-05,10-Q,0001193125-20-286983,USB_2020-11-05_10-Q_0001193125-20-286983_USBRE...,15002,Management's Discussion and Analysis — Credit ...,Management's Discussion and Analysis — Credit ...,le conclusions that could be significant to th...,,
3,USB,2021-05-04,10-Q,0001193125-21-150169,USB_2021-05-04_10-Q_0001193125-21-150169_USBRE...,13613,Management's Discussion and Analysis — Credit ...,Management's Discussion and Analysis — Credit ...,opment and the selection of critical accountin...,,
4,USB,2021-11-02,10-Q,0001193125-21-317037,USB_2021-11-02_10-Q_0001193125-21-317037_USBRE...,14708,Management's Discussion and Analysis — Credit ...,Management's Discussion and Analysis — Credit ...,opment and the selection of critical accountin...,,
5,USB,2022-05-03,10-Q,0001193125-22-138788,USB_2022-05-03_10-Q_0001193125-22-138788_USBRE...,12723,Management's Discussion and Analysis — Credit ...,Management's Discussion and Analysis — Credit ...,opment and the selection of critical accountin...,,
6,USB,2022-08-04,10-Q,0001193125-22-212040,USB_2022-08-04_10-Q_0001193125-22-212040_USBRE...,13271,Management's Discussion and Analysis — Credit ...,Management's Discussion and Analysis — Credit ...,elopment and the selection of critical account...,,
7,USB,2022-11-01,10-Q,0001193125-22-275036,USB_2022-11-01_10-Q_0001193125-22-275036_USBRE...,13556,Management's Discussion and Analysis — Credit ...,Management's Discussion and Analysis — Credit ...,opment and the selection of critical accountin...,,
8,USB,2023-05-08,10-Q,0001193125-23-137980,USB_2023-05-08_10-Q_0001193125-23-137980_USBRE...,12863,Management's Discussion and Analysis — Credit ...,Management's Discussion and Analysis — Credit ...,elopment and the selection of critical account...,,
9,USB,2023-08-07,10-Q,0001193125-23-204050,USB_2023-08-07_10-Q_0001193125-23-204050_USBRE...,13193,Management's Discussion and Analysis — Credit ...,Management's Discussion and Analysis — Credit ...,opment and the selection of critical accountin...,,
10,USB,2023-11-01,10-Q,0001193125-23-268341,USB_2023-11-01_10-Q_0001193125-23-268341_USBRE...,13073,Management's Discussion and Analysis — Credit ...,Management's Discussion and Analysis — Credit ...,opment and the selection of critical accountin...,,
11,USB,2024-05-01,10-Q,0000036104-24-000037,USB_2024-05-01_10-Q_0000036104-24-000037_USBRE...,11261,Management's Discussion and Analysis — Credit ...,Management's Discussion and Analysis — Credit ...,elopment and the selection of critical account...,,
12,USB,2024-08-06,10-Q,0000036104-24-000052,USB_2024-08-06_10-Q_0000036104-24-000052_USBRE...,12020,Management's Discussion and Analysis — Credit ...,Management's Discussion and Analysis — Credit ...,elopment and the selection of critical account...,,

In [48]:
USB_REVIEW_CSV = "/content/usb_13_review.csv"
usb_review_df.to_csv(USB_REVIEW_CSV, index=False)

print("Saved:", USB_REVIEW_CSV)

Saved: /content/usb_13_review.csv

In [49]:
from google.colab import files
files.download(USB_REVIEW_CSV)

In [50]:
import pandas as pd

correct_2 = pd.DataFrame([
    {
        "ticker": "AAPL",
        "filing_date": "2019-10-31",
        "filing_type": "10-K",
        "accession_number": "0000320193-19-000119",
        "repaired_filename": "AAPL_2019-10-31_10-K_0000320193-19-000119_FAMILY52.txt",
        "source_log": "family_rescue",
        "manual_label": "correct",
        "notes": "real MD&A heading and narrative start"
    },
    {
        "ticker": "KLAC",
        "filing_date": "2023-08-04",
        "filing_type": "10-K",
        "accession_number": "0000319201-23-000031",
        "repaired_filename": "KLAC_2023-08-04_10-K_0000319201-23-000031_FAMILY52.txt",
        "source_log": "family_rescue",
        "manual_label": "correct",
        "notes": "real MD&A heading and narrative start"
    }
])

CORRECT_2_CSV = "/content/correct_2_files.csv"
correct_2.to_csv(CORRECT_2_CSV, index=False)

print("Saved:", CORRECT_2_CSV)
display(correct_2)

Saved: /content/correct_2_files.csv

,ticker,filing_date,filing_type,accession_number,repaired_filename,source_log,manual_label,notes
0,AAPL,2019-10-31,10-K,0000320193-19-000119,AAPL_2019-10-31_10-K_0000320193-19-000119_FAMI...,family_rescue,correct,real MD&A heading and narrative start
1,KLAC,2023-08-04,10-K,0000319201-23-000031,KLAC_2023-08-04_10-K_0000319201-23-000031_FAMI...,family_rescue,correct,real MD&A heading and narrative start

In [51]:
from pathlib import Path
import shutil
import zipfile

SOURCE_DIR = OUT_DIR
DOWNLOAD_DIR = Path("/content/correct_2_txt")
DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)

# clear old files
for old_file in DOWNLOAD_DIR.glob("*.txt"):
    old_file.unlink()

copied = 0
missing = []

for _, row in correct_2.iterrows():
    fname = row["repaired_filename"]
    src = SOURCE_DIR / fname
    dst = DOWNLOAD_DIR / fname

    if src.exists():
        shutil.copy2(src, dst)
        copied += 1
    else:
        missing.append(fname)

print("Copied txt files:", copied)
print("Missing txt files:", len(missing))
if missing:
    print("Missing list:")
    for x in missing:
        print(x)

Copied txt files: 2
Missing txt files: 0

In [52]:
CORRECT_2_ZIP = "/content/correct_2_txt.zip"

with zipfile.ZipFile(CORRECT_2_ZIP, "w", zipfile.ZIP_DEFLATED) as zipf:
    for txt_file in DOWNLOAD_DIR.glob("*.txt"):
        zipf.write(txt_file, arcname=txt_file.name)

print("Saved zip:", CORRECT_2_ZIP)

Saved zip: /content/correct_2_txt.zip

In [53]:
from google.colab import files

files.download(CORRECT_2_CSV)
files.download(CORRECT_2_ZIP)

In [54]:
remaining_52 = pd.read_csv("remaining_52_files_rebuilt.csv")
correct_2 = pd.read_csv("/content/correct_2_files.csv")

for df in [remaining_52, correct_2]:
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["filing_type"] = df["filing_type"].astype(str).str.strip().str.upper()
    df["accession_number"] = df["accession_number"].astype(str).str.strip()
    df["filing_date"] = pd.to_datetime(df["filing_date"], errors="coerce").dt.strftime("%Y-%m-%d")

correct_2_keys = set(
    zip(
        correct_2["ticker"],
        correct_2["filing_date"],
        correct_2["filing_type"],
        correct_2["accession_number"]
    )
)

remaining_50 = remaining_52.loc[
    ~remaining_52.apply(
        lambda r: (r["ticker"], r["filing_date"], r["filing_type"], r["accession_number"]) in correct_2_keys,
        axis=1
    )
].copy()

REMAINING_50_CSV = "/content/remaining_50_files.csv"
remaining_50.to_csv(REMAINING_50_CSV, index=False)

print("Remaining unresolved files:", len(remaining_50))
print("Saved:", REMAINING_50_CSV)

Remaining unresolved files: 50
Saved: /content/remaining_50_files.csv

In [55]:
remaining_52 = pd.read_csv("remaining_52_files_rebuilt.csv")
correct_2 = pd.read_csv("/content/correct_2_files.csv")

for df in [remaining_52, correct_2]:
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["filing_type"] = df["filing_type"].astype(str).str.strip().str.upper()
    df["accession_number"] = df["accession_number"].astype(str).str.strip()
    df["filing_date"] = pd.to_datetime(df["filing_date"], errors="coerce").dt.strftime("%Y-%m-%d")

correct_2_keys = set(
    zip(
        correct_2["ticker"],
        correct_2["filing_date"],
        correct_2["filing_type"],
        correct_2["accession_number"]
    )
)

remaining_50 = remaining_52.loc[
    ~remaining_52.apply(
        lambda r: (r["ticker"], r["filing_date"], r["filing_type"], r["accession_number"]) in correct_2_keys,
        axis=1
    )
].copy()

REMAINING_50_CSV = "/content/remaining_50_files.csv"
remaining_50.to_csv(REMAINING_50_CSV, index=False)

print("Remaining unresolved files:", len(remaining_50))
print("Saved:", REMAINING_50_CSV)

Remaining unresolved files: 50
Saved: /content/remaining_50_files.csv